### PR TITLE
Evaluate special 'now' terms in Scylla Manager tasks only on task creation

### LINKED ISSUE #838: Scylla Manager task startDate is constantly updated
**Describe the bug**
Manager tasks defined in CRD having default startDate (`now`) are being rescheduled on every reconcilation. This is because `now` value is evaluated and compared with manager state. Of course it has a different value on each evaluation, hence task is updated.

**To Reproduce**
1. Define repair/backup task with default startDate
2. Update ScyllaCluster to trigger informers notification
3. Created task is updated with new startDate

**Expected behavior**
Start date `now` should be evaluated only on task creation.

### LINKED ISSUE #1510: Repair is triggered repeatedly
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In db logs we can find multiple repair requests (one node had 2249 occurrences over 12h test, see they appear in similar time):
```
INFO  2023-10-22 09:31:43,020 [shard  0] repair - repair[a8e797a8-5a76-48c3-8fbe-9b233b313883]: starting user-requested repair for keyspace keyspace1, repair id 789, options {{ hosts -> 172.20.36.24,172.20.25.170,172.20.67.101}, { columnFamilies -> standard1}, { ranges -> 9124434549921316097:9188838734908371860}}
INFO  2023-10-22 09:31:43,021 [shard  0] repair - repair[d5bb0e4c-4c45-4b64-820c-1ac88ed45851]: starting user-requested repair for keyspace keyspace1, repair id 790, options {{ hosts -> 172.20.25.170,172.20.67.101,172.20.36.24}, { columnFamilies -> standard1}, { ranges -> 9188838734908371860:9200963077934155553}}
INFO  2023-10-22 09:31:43,022 [shard  0] repair - repair[cebeb019-affe-4e55-9a5e-698c7752037d]: starting user-requested repair for keyspace keyspace1, repair id 791, options {{ hosts -> 172.20.36.24,172.20.67.101,172.20.25.170}, { columnFamilies -> standard1}, { ranges -> 9007611882491243037:9035715497213732394}}
WARN  2023-10-22 09:41:21,936 [shard  2] repair - repair[2839ee20-302a-415e-bfc1-0751e6eb31cd]: shard=2, keyspace=keyspace1, cf=standard1, range=(6451000176190542289, 6456358479733657758], got error in row level repair: std::system_error (No route to host)
WARN  2023-10-22 09:41:21,942 [shard  0] repair - repair[2839ee20-302a-415e-bfc1-0751e6eb31cd]: repair_tracker run failed: std::runtime_error ({shard 2: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(6451000176190542289, 6456358479733657758])})
```

## Impact

Repair is triggered over and over again

## How frequently does it reproduce?

don't know yet

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-13-g4bc44d9
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `0f64cf29-5ef7-45a7-98fe-e8c03223bf96`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60806e7b31f0e9351674ba718a5cdac8df07b86/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0f64cf29-5ef7-45a7-98fe-e8c03223bf96`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0f64cf29-5ef7-45a7-98fe-e8c03223bf96)
- Show all stored logs command: `$ hydra investigate show-logs 0f64cf29-5ef7-45a7-98fe-e8c03223bf96`

## Logs:
- **kubernetes-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/kubernetes-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/kubernetes-0f64cf29.tar.gz)
- **db-cluster-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/db-cluster-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/db-cluster-0f64cf29.tar.gz)
- **sct-runner-events-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-runner-events-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-runner-events-0f64cf29.tar.gz)
- **sct-0f64cf29.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-0f64cf29.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-0f64cf29.log.tar.gz)
- **loader-set-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/loader-set-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/loader-set-0f64cf29.tar.gz)
- **monitor-set-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/monitor-set-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/monitor-set-0f64cf29.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/86/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=0f64cf29-5ef7-45a7-98fe-e8c03223bf96)
</details>

### PR DESCRIPTION
**Pull request by zimnx**
Special 'now' value was evaluated on every ScyllaCluster reconcilation.
Because it's result is always different, task definition was always
different than the same task stored in Manager state.
Hence every task was constantly updated with newer startDate.

Fixes #838
Fixes #1510

### CODE REVIEW

File: pkg/controller/manager/sync_action.go [hunk 1]
```diff
@@ -6,10 +6,11 @@ import (
 	"context"
 	"fmt"
 	"reflect"
+	"strings"
 
 	"github.com/pkg/errors"
 	"github.com/scylladb/go-set/strset"
-	"github.com/scylladb/scylla-operator/pkg/api/scylla/v1"
+	v1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1"
```
Comment (tnozicka) [inline pkg/controller/manager/sync_action.go]: nit: do the rename commit first so you don't have to modify the same line in one PR

File: pkg/controller/manager/sync_action.go [hunk 2]
```diff
@@ -138,7 +139,12 @@ func syncBackupTasks(clusterID string, cluster *v1.ScyllaCluster, syncer stateCa
 			update := false
 			for _, managerTask := range managerState.BackupTasks {
 				if managerTask.ID == backupTask.ID {
+					// Keep special "now" value evaluated on task creation.
+					if strings.HasPrefix(backupTask.SchedulerTaskSpec.StartDate, "now") {
```
Comment (tnozicka) [inline pkg/controller/manager/sync_action.go:143]: would it be better to make a function so you don't have to repeat the parsing and you can unit test it?

**Review by tnozicka — COMMENTED** [review]
- pls update the CRD description accordingly
- shouldn't you set creationTimestamp on task create - it can be arbitrarily delayed

File: pkg/controller/manager/sync_action.go (hunk 1 above)
Comment (zimnx) [reply pkg/controller/manager/sync_action.go]: done

File: pkg/controller/manager/sync_action.go (hunk 2 above)
Comment (zimnx) [reply pkg/controller/manager/sync_action.go]: done

**Comment by zimnx** [comment]
> * pls update the CRD description accordingly
done
> * shouldn't you set creationTimestamp on task create - it can be arbitrarily delayed
startDate cannot be in the past, so it's evaluated at reconcilation when task is about to be created with some extra buffer (30s) for 'now' startDate.

File: pkg/controller/manager/sync_action.go [hunk 3]
```diff
@@ -201,6 +204,19 @@ func syncRepairTasks(clusterID string, cluster *scyllav1.ScyllaCluster, syncer s
 	return actions, nil
 }
 
+type startDateGetSetter interface {
```
Comment (tnozicka) [inline pkg/controller/manager/sync_action.go:207]: nit: `startDateGetterSetter` or `startDateInterface`
on the other hand would it work with just inheritance?

File: pkg/controller/manager/sync_test.go [hunk 4]
```diff
@@ -355,3 +467,139 @@ func actionComparer(a action, b action) bool {
...
+		test := ts[i]
+		t.Run(test.name, func(t *testing.T) {
+			t.Parallel()
+
+			changed := taskChanged(test.spec, test.managerTask)
+			if changed && !test.expected {
+				t.Error("expected no task change, but it's detected")
+			} else if !changed && test.expected {
+				t.Error("expected task change, but it's not detected")
+			}
```
Comment (tnozicka) [inline pkg/controller/manager/sync_test.go:534]:
```
if changed != expected {
    t.Errorf("expected %v, got %v```

File: pkg/controller/manager/sync_test.go [hunk 5]
```diff
@@ -355,3 +467,139 @@ func actionComparer(a action, b action) bool {
...
+		},
+	}
+
+	for i := range ts {
+		test := ts[i]
+		t.Run(test.name, func(t *testing.T) {
+			t.Parallel()
+
+			changed := taskChanged(test.spec, test.managerTask)
+			if changed && !test.expected {
```
Comment (tnozicka) [inline pkg/controller/manager/sync_test.go:598]: same here

**Review by tnozicka — COMMENTED** [review]
last time we talked about `now` being an alias to `creationTimestamp`, I suppose this just wasn't update yet, right?

**Comment by zimnx** [comment]
> last time we talked about `now` being an alias to `creationTimestamp`, I suppose this just wasn't update yet, right?

I validated and manager server rejects tasks with date in the past

File: pkg/controller/manager/sync_test.go [hunk 6]
```diff
@@ -305,6 +305,118 @@ func TestManagerSynchronization(t *testing.T) {
...
+						},
+						ID: "repair-id",
+					},
+				},
+			},
+
+			Actions: nil,
+		},
+		{
+			Name: "Update task when startDate is changed",
```
Comment (rzetelskik) [inline pkg/controller/manager/sync_test.go:365]: nit: It'd be better to make the tests' names grammatically concise, i.e. if the first test's name is "Special 'now' startDate is not compared during update decision", the other should also say e.g. "Task gets updated when startDate is changed".

File: pkg/controller/manager/sync_test.go [hunk 7]
```diff
@@ -355,3 +467,139 @@ func actionComparer(a action, b action) bool {
...
+		expected    bool
+	}{
+		{
+			name:        "equal empty tasks",
+			spec:        &BackupTask{},
+			managerTask: &BackupTask{},
+			expected:    false,
+		},
+		{
+			name: "different schedule task",
```
Comment (rzetelskik) [inline pkg/controller/manager/sync_test.go:485]: ditto

File: pkg/controller/manager/sync_test.go [hunk 8]
```diff
@@ -355,3 +467,139 @@ func actionComparer(a action, b action) bool {
...
+		expected    bool
+	}{
+		{
+			name:        "equal empty tasks",
+			spec:        &RepairTask{},
+			managerTask: &RepairTask{},
+			expected:    false,
+		},
+		{
+			name: "different schedule task",
```
Comment (rzetelskik) [inline pkg/controller/manager/sync_test.go:553]: ditto

File: pkg/controller/manager/sync_action.go (hunk 3 above)
Comment (zimnx) [reply pkg/controller/manager/sync_action.go]: renamed, would you mind showing a pseudocode for what you have in mind regarding last part?

File: pkg/controller/manager/sync_test.go (hunk 4 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go]: done

File: pkg/controller/manager/sync_test.go (hunk 5 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go]: done

File: pkg/controller/manager/sync_test.go (hunk 6 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go]: done

File: pkg/controller/manager/sync_test.go (hunk 7 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go]: done

File: pkg/controller/manager/sync_test.go (hunk 8 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go]: done

File: pkg/controller/manager/sync_action.go [hunk 9]
```diff
@@ -201,14 +204,27 @@ func syncRepairTasks(clusterID string, cluster *v1.ScyllaCluster, syncer stateCa
...
 
+type startDateGetterSetter interface {
+	GetStartDate() string
+	SetStartDate(sd string)
+}
+
+func taskChanged(spec, managerTask startDateGetterSetter) bool {
+	// Keep special "now" value evaluated on task creation.
+	if strings.HasPrefix(spec.GetStartDate(), "now") {
+		spec.SetStartDate(managerTask.GetStartDate())
```
Comment (tnozicka) [inline pkg/controller/manager/sync_action.go:215]: this operation is quite hidden for the caller given the function name and it seems to transitively write into a shared informer

Comment (zimnx) [reply pkg/controller/manager/sync_action.go:217]: good catch, fixed into writing into a copy

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign tnozicka

File: pkg/controller/manager/sync_action.go (hunk 9 above)
Comment (tnozicka) [reply pkg/controller/manager/sync_action.go:217]: @zimnx as rewriting the startDate doesn't really fit into the scope of `taskChanged`, can you pls extract it to a defaulting function, say `evaluateDates`, and call it right after the `DeepCopy` in `syncRepairTasks` and `syncBackupTasks`?

**Review by tnozicka — COMMENTED** [review]
one pending comment, rest lgtm

**Review by tnozicka — APPROVED** [review]
thanks for the updates
/approve

/assign @rzetelskik

**Comment by zimnx** [comment]
Flake:
https://github.com/scylladb/scylla-operator/issues/1525

/test e2e-gke-parallel

**Comment by zimnx** [comment]
Flakes:
https://github.com/scylladb/scylla-operator/issues/1433
https://github.com/scylladb/scylla-operator/issues/1525

/test e2e-gke-parallel

**Comment by fruch** [comment]
Hallelujah

**Comment by rzetelskik** [comment]
Belated happy (2nd) birthday to this PR! :tada:
