### PR TITLE
Fix accidental ignition and stuck graceful termination

### LINKED ISSUE #2213: ScyllaDB container starts before it's ignited
I've seen ScyllaDB container starting before the ignition finishes because the file is touched too early. Running ScyllaDB before tuning is done will skew the results. (Rolling updates are correctly blocked by the full pod readiness.)

The following comes from an e2e to validate such scenario
https://github.com/tnozicka/scylla-operator/commit/995e3a5506aa854e7343905082f804b7aacc390a

```
NodeConfig Optimizations [It] should correctly project state for each scylla pod [Serial]
/home/dev/dev/go/src/github.com/scylladb/scylla-operator-1/test/e2e/set/nodeconfig/nodeconfig_optimizations.go:194

  [FAILED] container in Pod "basic-dwtd8-us-east-1-us-east-1a-0" don't match the expected state
  Expected
      <map[string]bool | len:5>: {
          "scylladb-ignition": false,
          "sidecar-injection": true,
          "scylla": true,
          "scylla-manager-agent": true,
          "scylladb-api-status-probe": true,
      }
  to have {key: value}
      <map[interface {}]interface {} | len:1>: {
          <string>"scylla": <bool>false,
      }
  In [It] at: /home/dev/dev/go/src/github.com/scylladb/scylla-operator-1/test/e2e/set/nodeconfig/nodeconfig_optimizations.go:342 
```

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR fixes the ignition touching the file before it's actually ignited and adds e2e coverage to prevent it from happening again. (Looks like it got broken in the early iterations.)

It also fixes stuck graceful termination *before* ignition is done because fixing one surfaces the other is broken and they can't be split without disabling some tests. (For this reason the ignition file is changed twice - best viewed as an overall diff then "by commit"). It also fixes graceful termination *after* ignition that was broken because of the manager agent container wasn't using `exec`. (@rzetelskik found that previously and it also failed in the test I wrote.)

**Which issue is resolved by this Pull Request:**
Resolves #2213

### CODE REVIEW

**Comment by tnozicka** [comment]
(the e2e test on it's own failed as expected - the run was https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2212/pull-scylla-operator-master-e2e-gke-serial/1862139318282227712#1:test-build-log.txt%3A994)

**Review by zimnx — APPROVED** [review]

File: test/e2e/set/nodeconfig/nodeconfig_optimizations.go [hunk 1]
```diff
@@ -328,6 +329,25 @@ var _ = g.Describe("NodeConfig Optimizations", framework.Serial, func() {
...
+		o.Expect(scPods.Items).NotTo(o.BeEmpty())
+
+		for _, pod := range scPods.Items {
+			crm := utils.GetContainerReadinessMap(&pod)
+			o.Expect(crm).To(
+				o.And(
+					o.HaveKeyWithValue(naming.ScyllaContainerName, false),
+					o.HaveKeyWithValue(naming.ScyllaDBIgnitionContainerName, false),
+				),
+				fmt.Sprintf("container in Pod %q don't match the expected state", pod.Name),
```
[the remark this answers is not in the document]
Comment (tnozicka) [reply test/e2e/set/nodeconfig/nodeconfig_optimizations.go:347]: ok, I suppose `container(s)` as it's 1-N

**Comment by tnozicka** [comment]
now that we actually wait for ignition - the tuning took over 9 minutes which made the job timeout
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2212/pull-scylla-operator-master-e2e-gke-serial/1862151638882455552/artifacts/e2e/cluster-0/namespaces/e2e-test-nodeconfig-z4wpb-0-j4m2b/pods/basic-8l7bn-us-east-1-us-east-1a-0/scylladb-ignition.current

**Comment by tnozicka** [comment]
blocked on https://github.com/scylladb/scylla-operator/issues/2216

**Comment by tnozicka** [comment]
I've finally traced the failed serial tests ona GKE cluster - indicating graceful termination issues
```
Dec 04 17:15:13 gke-so-753fb68c-ed81-4a23-aa2-workers-24a06bcc-636c kubelet[38896]: I1204 17:15:13.553585   38896 kuberuntime_container.go:647] "PreStop hook completed" pod="e2e-test-nodeconfig-sf5hl-0-ss4tc/basic-rk6zh-us-east-1-us-east-1a-0" podUID="b01f1990-37ff-4da0-8a50-1b39c3024663" containerName="scylla" containerID="containerd://c3d9dd8656b21c701f5ead2387f30d898a1ebc6a58b5d9edf982f184b28033eb"
Dec 04 17:15:13 gke-so-753fb68c-ed81-4a23-aa2-workers-24a06bcc-636c kubelet[38896]: I1204 17:15:13.553605   38896 kuberuntime_container.go:745] "Killing container with a grace period" pod="e2e-test-nodeconfig-sf5hl-0-ss4tc/basic-rk6zh-us-east-1-us-east-1a-0" podUID="b01f1990-37ff-4da0-8a50-1b39c3024663" containerName="scylla" containerID="containerd://c3d9dd8656b21c701f5ead2387f30d898a1ebc6a58b5d9edf982f184b28033eb" gracePeriod=885
Dec 04 17:29:58 gke-so-753fb68c-ed81-4a23-aa2-workers-24a06bcc-636c kubelet[38896]: I1204 17:29:58.725803   38896 kuberuntime_container.go:754] "Container exited normally" pod="e2e-test-nodeconfig-sf5hl-0-ss4tc/basic-rk6zh-us-east-1-us-east-1a-0" podUID="b01f1990-37ff-4da0-8a50-1b39c3024663" containerName="scylla" containerID="containerd://c3d9dd8656b21c701f5ead2387f30d898a1ebc6a58b5d9edf982f184b28033eb"
```

**Comment by tnozicka** [comment]
#2246 landed
/test all

**Review by zimnx — COMMENTED** [review]
One comment, otherwise lgtm. Please fix PR description, one sentence contains duplicated parts.

File: test/e2e/set/scyllacluster/scyllacluster_restarts.go [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+
+		scyllaclusterverification.Verify(ctx, f.KubeClient(), f.ScyllaClient(), sc)
+
+		framework.By("Fetching the Pod and validating container readiness")
+		podName := naming.PodNameForScyllaCluster(sc.Spec.Datacenter.Racks[0], sc, 0)
+		pod, err := f.KubeClient().CoreV1().Pods(f.Namespace()).Get(ctx, podName, metav1.GetOptions{})
+		o.Expect(err).NotTo(o.HaveOccurred())
+
+		pod, err = f.KubeClient().CoreV1().Pods(f.Namespace()).Get(ctx, podName, metav1.GetOptions{})
+		o.Expect(err).NotTo(o.HaveOccurred())
```
[the remark this answers is not in the document]
Comment (tnozicka) [reply test/e2e/set/scyllacluster/scyllacluster_restarts.go]: fixed, thx

**Comment by tnozicka** [comment]
> Please fix PR description, one sentence contains duplicated parts.

I fixed the typos and added more context, but one fix is for graceful termination *before* ignition and the other fix is *after* ignition.

**Review by zimnx — APPROVED** [review]
lgtm
/assign rzetelskik

File: test/e2e/set/nodeconfig/nodeconfig_optimizations.go [hunk 3]
```diff
@@ -400,7 +421,20 @@ var _ = g.Describe("NodeConfig Optimizations", framework.Serial, func() {
...
+		scyllaclusterverification.VerifyWithOptions(
+			ctx,
+			f.KubeClient(),
+			f.ScyllaClient(),
+			sc,
+			scyllaclusterverification.VerifyOptions{
+				VerifyStatefulSetOptions: scyllaclusterverification.VerifyStatefulSetOptions{
+					PodRestartCountAssertion: func(a o.Assertion, containerName, podName string) {
+						// We expect restart(s) from the startup probe, usually 1.
+						a.To(o.BeNumerically("<=", 2), fmt.Sprintf("container %q in pod %q should not be restarted by the startup probe more than twice", containerName, podName))
```
Comment (rzetelskik) [inline test/e2e/set/nodeconfig/nodeconfig_optimizations.go:433]: Not sure I understand this right - isn't this testing a side effect? If you lowered the period of the startup probe, or the timeout (which according to [this TODO](https://github.com/scylladb/scylla-operator/blob/d4da9dfe44e55d7dd674a3d0394eafb5f309af2f/pkg/controller/scylladbdatacenter/resource.go#L784) should have already had been done), won't it introduce flakiness?

**Review by rzetelskik — COMMENTED** [review]
one comment/question, rest lgtm

File: test/e2e/set/nodeconfig/nodeconfig_optimizations.go (hunk 3 above)
Comment (tnozicka) [reply test/e2e/set/nodeconfig/nodeconfig_optimizations.go:433]: Nope, my understanding is that this would straight fail and you'd need to adjust the value. Similarly the 10m30s sleep should be adjusted as well.

Comment (rzetelskik) [reply test/e2e/set/nodeconfig/nodeconfig_optimizations.go:433]: ok, let's give this a try

**Comment by tnozicka** [comment]
bug https://github.com/scylladb/scylla-operator/issues/2249
/retest
