### PR TITLE
Remove the PVC when the service is decommissioned

### LINKED ISSUE #670: Removing additional rack member makes it's PVC stay undeleted and hold PV bound
**Describe the bug**
If we add new rack to an existing Scylla cluster and then decommission it we get PVC undeleted which holds PV bound:

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                 STORAGECLASS       REASON   AGE     VOLUMEMODE
local-pv-1314e26a                          3537Gi     RWO            Delete           Bound    scylla/data-sct-cluster-us-east1-b-us-east1-1                         local-raid-disks            4h12m   Filesystem
local-pv-d3c294f3                          3537Gi     RWO            Delete           Bound    scylla/data-sct-cluster-us-east1-b-us-east1-0                         local-raid-disks            4h12m   Filesystem
local-pv-e608cfb                           3537Gi     RWO            Delete           Bound    scylla/data-sct-cluster-us-east1-b-us-east1-2                         local-raid-disks            4h12m   Filesystem
local-pv-fc94055                           3537Gi     RWO            Delete           Bound    scylla/data-sct-cluster-us-east1-b-us-east1-1-0                       local-raid-disks            4h12m   Filesystem
pvc-a6690164-4ad1-406a-8d24-ae2c42458650   10Gi       RWO            Delete           Bound    minio/minio                                                           gp2                         4h15m   Filesystem
pvc-c12f4035-8c65-4991-9e71-770b28007ca5   10Gi       RWO            Delete           Bound    scylla-manager-system/data-scylla-manager-manager-dc-manager-rack-0   gp2                         4h14m   Filesystem
```

```
NAMESPACE               NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE     VOLUMEMODE
minio                   minio                                           Bound         pvc-a6690164-4ad1-406a-8d24-ae2c42458650   10Gi       RWO            gp2                4h15m   Filesystem
scylla-manager-system   data-scylla-manager-manager-dc-manager-rack-0   Bound         pvc-c12f4035-8c65-4991-9e71-770b28007ca5   10Gi       RWO            gp2                4h15m   Filesystem
scylla                  data-sct-cluster-us-east1-b-us-east1-0          Bound         local-pv-d3c294f3                          3537Gi     RWO            local-raid-disks   4h13m   Filesystem
scylla                  data-sct-cluster-us-east1-b-us-east1-1          Bound         local-pv-1314e26a                          3537Gi     RWO            local-raid-disks   4h9m    Filesystem
scylla                  data-sct-cluster-us-east1-b-us-east1-1-0        Bound         local-pv-fc94055                           3537Gi     RWO            local-raid-disks   3h30m   Filesystem
scylla                  data-sct-cluster-us-east1-b-us-east1-2          Terminating   local-pv-e608cfb                           3537Gi     RWO            local-raid-disks   4h5m    Filesystem
scylla                  data-sct-cluster-us-east1-b-us-east1-3          Pending                                                                            local-raid-disks   3h13m   Filesystem
```

**To Reproduce**
1. Deploy Scylla operator
2. Deploy Scylla cluster consisting of 1 rack and 3 members in it
3. Deploy additional rack with 1 member in it.
4. Decommission newly added rack and it's member
5. Look at the PVs and PVCs and see that PV stays bound and PVC undeleted

**Expected behavior**
PVC that is related to deleted/decommissioned scylla pod must be deleted and it's PV must be unbound.

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.
[kubernetes-c76f9a3f.tar.gz](https://github.com/scylladb/scylla-operator/files/6748547/kubernetes-c76f9a3f.tar.gz)

**Environment:**
 - Platform: EKS
 - Kubernetes version: 1.20.4
 - Scylla version: 4.4.2
 - Scylla-operator version: e.g.: v1.4.0-alpha.0-34-gf13771d

**Additional context**

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
When a member is decommissioned we need to delete the PVC because a new scylla wouldn't bootstrap from it after the decommissioning process. Like in the case of a scaling down and up again. This is similar to what we have done in https://github.com/scylladb/scylla-operator/blob/b3413fcdd6c100dbb701d620a6428dc057faaf17/pkg/controllers/cluster/cleanup.go#L162-L165

We can't easily reconcile the PVC to match the intent in general, because PVCs are half managed by StatefulSet controller, don't have ownerRefs and user may expect those to stay around. So if you scale down the rack we will remove the PVC, but removing the whole rack won't be reconciled. And there are some race like when a StatefulSet is created before the Service and then the rack is scaled back down. Those are preexisting though.

**Which issue is resolved by this Pull Request:**
Resolves #670 #669

### CODE REVIEW

**Comment by zimnx** [comment]
This may lead to data loss if PV ReclaimPolicy is set to Delete, that's why StatefulSet doesn't clean it automatically when pod is removed. I think we need at least a way to opt out from PVC cleanup.

**Comment by tnozicka** [comment]
My understanding is that the behaviour was preexisting and this PR is just fixing a leftover. Although I am not excited about deleting PVCs, removing a PVC for a decommissioned node shouldn't loose data as it was drained and balanced to the other nodes, right? You could still setup the PVs with Retain policy to keep the data and still allow for scale down+up to work.

**Comment by tnozicka** [comment]
(clean rebase)

**Comment by tnozicka** [comment]
(clean rebase)

File: test/e2e/set/scyllacluster/verify.go [hunk 1]
```diff
@@ -12,14 +14,52 @@ import (
...
+			expectedPvcNames = append(expectedPvcNames, naming.PVCNameForStatefulSet(stsName, ord))
+		}
+	}
+
+	sort.Strings(scPVCNames)
+	sort.Strings(expectedPvcNames)
+	o.Expect(scPVCNames).To(o.BeEquivalentTo(expectedPvcNames))
+}
+
+func verifyStatefulset(ctx context.Context, sts *appsv1.StatefulSet, coreClient corev1client.CoreV1Interface) {
```
Comment (zimnx) [inline test/e2e/set/scyllacluster/verify.go:57]: coreClient isn't used

**Review by zimnx — COMMENTED** [review]
one nit

File: test/e2e/set/scyllacluster/verify.go (hunk 1 above)
Comment (tnozicka) [reply test/e2e/set/scyllacluster/verify.go:57]: good catch

Comment (tnozicka) [reply test/e2e/set/scyllacluster/verify.go]: fixed

**Comment by tnozicka** [comment]
(clean rebase)

**Review by zimnx — APPROVED** [review]
lgtm, thanks
