### PR TITLE
Validate whether Scylla container is tuned before Pod is unblocked

### LINKED ISSUE #1856: Scylla Pod is unblocked even when tuning fails
Operator Sidecar waits until all matching NodeConfig's are done with tuning, but it only validates whether Node where given Pod is running is done. It doesn't wait until Scylla container is tuned.

This causes that E2E validating our node tuning gives us a false positive, as even when tuning fails, Scylla Pod is started.

### PR DESCRIPTION
**Pull request by zimnx**
Scylla Pod was unblocked even when container wasn't yet tuned. E2E validating node optimizations wasn't validating it either giving us a false positive.

Fixes #1856

### CODE REVIEW

File: pkg/controllerhelpers/scylla_test.go [hunk 1]
```diff
@@ -781,3 +781,103 @@ func TestGetRequiredScyllaHosts(t *testing.T) {
...
+				},
+			},
+			nodeName:      "node1",
+			containerID:   "container-id",
+			expectedTuned: true,
+		},
+	}
+
+	for i := range tt {
+		tc := tt[i]
```
Comment (tnozicka) [inline pkg/controllerhelpers/scylla_test.go:873]: 1.22+ is now enforce so this is no longer needed

**Review by tnozicka — APPROVED** [review]
/approve
lgtm, modulo one nit

File: pkg/controllerhelpers/scylla_test.go (hunk 1 above)
Comment (zimnx) [reply pkg/controllerhelpers/scylla_test.go]: done

**Comment by tnozicka** [comment]
/lgtm
thanks

**Comment by zimnx** [comment]
Provisioning failed + https://github.com/scylladb/scylla-operator/issues/1802#issuecomment-2025678115

/retest
