### PR TITLE
Stop any ongoing cleanup on Job termination and on cleanup startup

### LINKED ISSUE #1343: Cleanup is triggered multiple times
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Looks like cleanup is triggered multiple times when node is added up. I noticed during first cluster setup, after adding second node
```
2023-08-21 09:26:15.981: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=52e19381-a5c5-4d47-9175-efc4d252b894: type=RUNTIME_ERROR regex=std::runtime_error line_number=3954 node=sct-cluster-us-east1-b-us-east1-0
ERROR 2023-08-21 09:26:15,917 [shard 0] api - Failed force_keyspace_cleanup of system_schema.table{name=columns, id=24101c25-a2ae-3af7-87c1-b40ee1aca33f}: std::runtime_error (cleanup request failed: there is an ongoing cleanup on system_schema.columns)
```
In operator logs after adding second node we can see two pods `cleanup-sct-cluster-us-east1-b-us-east1-0` created:
```
2023-08-21T09:54:33Z   2023-08-21T10:09:08Z   2       scyllacluster-controller                                                             Normal    FinishedReplacingNode          New pod scylla/sct-cluster-us-east1-b-us-east1-1 is ready.
2023-08-21T09:49:50Z   2023-08-21T10:09:08Z   4       scyllacluster-controller                                                             Normal    ServiceUpdated                 Service scylla/sct-cluster-us-east1-b-us-east1-1 updated
2023-08-21T09:21:12Z   2023-08-21T10:09:08Z   8       scyllacluster-controller                                                             Normal    ServiceUpdated                 Service scylla/sct-cluster-us-east1-b-us-east1-1 updated
FirstSeen              LastSeen               Count   From                                                                                 Type      Reason                         Message
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       default-scheduler                                                                    Normal    Scheduled                      Successfully assigned scylla/cleanup-sct-cluster-us-east1-b-us-east1-0-ll45w to gke-longev-scylla-operat--loader-pool-725469ae-f6bx
2023-08-21T09:25:58Z   2023-08-21T09:25:58Z   1       kubelet                                                                              Normal    Pulling                        Pulling image "scylladb/scylla-operator:1.10.0-rc.0"
2023-08-21T09:26:15Z   2023-08-21T09:26:15Z   1       kubelet                                                                              Normal    Pulled                         Successfully pulled image "scylladb/scylla-operator:1.10.0-rc.0" in 17.555235585s (17.555247635s including waiting)
2023-08-21T09:26:15Z   2023-08-21T09:26:15Z   1       kubelet                                                                              Normal    Created                        Created container cleanup
2023-08-21T09:26:15Z   2023-08-21T09:26:15Z   1       kubelet                                                                              Normal    Started                        Started container cleanup
2023-08-21T09:26:16Z   2023-08-21T09:26:16Z   1       kubelet                                                                              Normal    Killing                        Stopping container cleanup
2023-08-21T09:25:58Z   2023-08-21T09:25:58Z   1       default-scheduler                                                                    Normal    Scheduled                      Successfully assigned scylla/cleanup-sct-cluster-us-east1-b-us-east1-0-sb762 to gke-longev-scylla-operat--loader-pool-725469ae-f6bx
2023-08-21T09:25:58Z   2023-08-21T09:25:58Z   1       kubelet                                                                              Normal    Pulling                        Pulling image "scylladb/scylla-operator:1.10.0-rc.0"
2023-08-21T09:26:15Z   2023-08-21T09:26:15Z   1       kubelet                                                                              Normal    Pulled                         Successfully pulled image "scylladb/scylla-operator:1.10.0-rc.0" in 16.980633752s (16.980680189s including waiting)
2023-08-21T09:26:15Z   2023-08-21T09:26:18Z   2       kubelet                                                                              Normal    Created                        Created container cleanup
2023-08-21T09:26:15Z   2023-08-21T09:26:18Z   2       kubelet                                                                              Normal    Started                        Started container cleanup
2023-08-21T09:26:18Z   2023-08-21T09:26:18Z   1       kubelet                                                                              Normal    Pulled                         Container image "scylladb/scylla-operator:1.10.0-rc.0" already present on machine
2023-08-21T09:25:57Z   2023-08-21T09:25:58Z   2       scyllacluster-controller                                                             Normal    JobCreated                     Job scylla/cleanup-sct-cluster-us-east1-b-us-east1-0 created
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       job-controller                                                                       Normal    SuccessfulCreate               Created pod: cleanup-sct-cluster-us-east1-b-us-east1-0-ll45w
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       scyllacluster-controller                                                             Normal    JobDeleted                     Job scylla/cleanup-sct-cluster-us-east1-b-us-east1-0 deleted
2023-08-21T09:25:58Z   2023-08-21T09:25:58Z   1       job-controller                                                                       Normal    SuccessfulCreate               Created pod: cleanup-sct-cluster-us-east1-b-us-east1-0-sb762
2023-08-21T09:26:21Z   2023-08-21T09:26:21Z   1       job-controller                                                                       Normal    Completed                      Job completed
2023-08-21T09:26:21Z   2023-08-21T09:26:21Z   1       scyllacluster-controller                                                             Normal    JobDeleted                     Job scylla/cleanup-sct-cluster-us-east1-b-us-east1-0 deleted
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       default-scheduler                                                                    Normal    Scheduled                      Successfully assigned scylla/cleanup-sct-cluster-us-east1-b-us-east1-1-nfgzc to gke-longev-scylla-operat--loader-pool-725469ae-x0cb
2023-08-21T09:25:58Z   2023-08-21T09:25:58Z   1       kubelet                                                                              Normal    Pulling                        Pulling image "scylladb/scylla-operator:1.10.0-rc.0"
2023-08-21T09:26:01Z   2023-08-21T09:26:01Z   1       kubelet                                                                              Normal    Pulled                         Successfully pulled image "scylladb/scylla-operator:1.10.0-rc.0" in 3.539337216s (3.539367347s including waiting)
2023-08-21T09:26:01Z   2023-08-21T09:26:01Z   1       kubelet                                                                              Normal    Created                        Created container cleanup
2023-08-21T09:26:01Z   2023-08-21T09:26:01Z   1       kubelet                                                                              Normal    Started                        Started container cleanup
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       scyllacluster-controller                                                             Normal    JobCreated                     Job scylla/cleanup-sct-cluster-us-east1-b-us-east1-1 created
2023-08-21T09:25:57Z   2023-08-21T09:25:57Z   1       job-controller                                                                       Normal    SuccessfulCreate               Created pod: cleanup-sct-cluster-us-east1-b-us-east1-1-nfgzc
2023-08-21T09:26:06Z   2023-08-21T09:26:06Z   1       job-controller                                                                       Normal    Completed                      Job completed
2023-08-21T09:26:06Z   2023-08-21T09:26:06Z   1       scyllacluster-controller                                                             Normal    JobDeleted                     Job scylla/cleanup-sct-cluster-us-east1-b-us-east1-1 deleted
```

## Impact

Cleanup triggered multiple times. Even when another one is already being run.

## How frequently does it reproduce?

Not sure yet.

## Installation details

Kernel Version: 5.15.0-1038-gke
Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`

Operator Image: scylladb/scylla-operator:1.10.0-rc.0
Operator Helm Version: 1.10.0-rc.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 3 nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylladb:2023.1.0` (k8s-gke: undefined_region)

Test: `longevity-scylla-operator-3h-gke-terminate-replace`
Test id: `8dbc3c51-b162-4349-8ed8-32fedc89efbf`
Test name: `scylla-operator/operator-1.10/gke/longevity-scylla-operator-3h-gke-terminate-replace`
Test config file(s):

- [longevity-scylla-operator-3h-terminate-replace.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8f6793e933aaa6aea083b30643ee029fe4b644c8/test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-replace.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8dbc3c51-b162-4349-8ed8-32fedc89efbf`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8dbc3c51-b162-4349-8ed8-32fedc89efbf)
- Show all stored logs command: `$ hydra investigate show-logs 8dbc3c51-b162-4349-8ed8-32fedc89efbf`

## Logs:
- **kubernetes-8dbc3c51.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/kubernetes-8dbc3c51.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/kubernetes-8dbc3c51.tar.gz)
- **db-cluster-8dbc3c51.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/db-cluster-8dbc3c51.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/db-cluster-8dbc3c51.tar.gz)
- **sct-runner-events-8dbc3c51.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/sct-runner-events-8dbc3c51.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/sct-runner-events-8dbc3c51.tar.gz)
- **sct-8dbc3c51.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/sct-8dbc3c51.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/sct-8dbc3c51.log.tar.gz)
- **loader-set-8dbc3c51.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/loader-set-8dbc3c51.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/loader-set-8dbc3c51.tar.gz)
- **parallel-timelines-report-8dbc3c51.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/parallel-timelines-report-8dbc3c51.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8dbc3c51-b162-4349-8ed8-32fedc89efbf/20230821_121420/parallel-timelines-report-8dbc3c51.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.10/job/gke/job/longevity-scylla-operator-3h-gke-terminate-replace/4/)
[Argus](https://argus.scylladb.com/test/5a6c4929-05fa-4ad6-bac5-7f970bafe9f7/runs?additionalRuns[]=8dbc3c51-b162-4349-8ed8-32fedc89efbf)
</details>

### PR DESCRIPTION
**Pull request by zimnx**
**Description of your changes:**

In case when Cleanup Job needs to be recreated by the Operator, the new
Job could complain about that it cannot execute cleanup operation, because there's
already one running.
Also when user would observe that maintenance operations have too big
impact on cluster performance he could decide to stop the cleanup.
Explicit stop is required as Scylla keeps cleaning even when API request
client disconnects.

In case when Cleanup Job was terminated ungracefully, a cleanup might
still be running in Scylla. As we can't keep track of it, a new one
needs to be started from the begining. To overcome an error returned by
Scylla API when cleanup is triggered and there's still one running, we
will stop all ongoing cleanups at the begining.

With this change all ongoing cleanup compactions are stopped when Cleanup Job terminates
due to received stop signal, and on each cleanup startup.

**Which issue is resolved by this Pull Request:**

Resolves #1343

### CODE REVIEW

File: pkg/cmd/operator/cleanupjob.go [hunk 1]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+	select {
+	case <-stopCh:
+		klog.InfoS("Stopping any ongoing cleanup")
+		stopCleanupCtx, stopCleanupCtxCancel := context.WithTimeout(context.Background(), stopCleanupOperationTimeout)
+		defer stopCleanupCtxCancel()
+
+		err := o.scyllaClient.StopCleanup(stopCleanupCtx, o.NodeAddress)
+		if err != nil {
+			klog.Warningf("Failed to stop cleanup: %s", err)
+			errs = append(errs, fmt.Errorf("can't stop the cleanup: %w", err))
```
Comment (rzetelskik) [inline pkg/cmd/operator/cleanupjob.go:147]: nit: be consistent about article usage (you didn't use *the* cleanup in previous errors, so don't use it here, I think we can treat it as a proper noun)

File: pkg/cmd/operator/cleanupjob.go [hunk 2]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
 	go func() {
 		<-stopCh
 		cancel()
 	}()
 
+	var errs []error
+
+	err := o.runCleanup(ctx)
+	if err != nil {
+		errs = append(errs, fmt.Errorf("can't cleanup: %w", err))
```
Comment (rzetelskik) [inline pkg/cmd/operator/cleanupjob.go:135]:
```suggestion
		errs = append(errs, fmt.Errorf("can't run cleanup: %w", err))
```

File: pkg/cmd/operator/cleanupjob.go [hunk 3]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+		if err != nil {
+			klog.Warningf("Failed to stop cleanup: %s", err)
+			errs = append(errs, fmt.Errorf("can't stop the cleanup: %w", err))
+		}
+	default:
+	}
+
+	err = apierrors.NewAggregate(errs)
+	if err != nil {
+		return fmt.Errorf("can't cleanup: %w", err)
```
Comment (rzetelskik) [inline pkg/cmd/operator/cleanupjob.go:154]:
```suggestion
		return fmt.Errorf("can't clean up: %w", err)
```

File: pkg/cmd/operator/cleanupjob.go [hunk 4]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+
+	select {
+	case <-stopCh:
+		klog.InfoS("Stopping any ongoing cleanup")
+		stopCleanupCtx, stopCleanupCtxCancel := context.WithTimeout(context.Background(), stopCleanupOperationTimeout)
+		defer stopCleanupCtxCancel()
+
+		err := o.scyllaClient.StopCleanup(stopCleanupCtx, o.NodeAddress)
+		if err != nil {
+			klog.Warningf("Failed to stop cleanup: %s", err)
```
Comment (rzetelskik) [inline pkg/cmd/operator/cleanupjob.go:146]: %s for error?

**Review by rzetelskik — COMMENTED** [review]
a few nits, other than that /lgtm

File: pkg/cmd/operator/cleanupjob.go (hunk 4 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:146]: `%w` isn't supported, in this branch `%s` and `%v` give the same output.

File: pkg/cmd/operator/cleanupjob.go (hunk 3 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go]: done

File: pkg/cmd/operator/cleanupjob.go (hunk 2 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go]: done

File: pkg/cmd/operator/cleanupjob.go [hunk 5]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+
+	select {
+	case <-stopCh:
+		klog.InfoS("Stopping any ongoing cleanup")
+		stopCleanupCtx, stopCleanupCtxCancel := context.WithTimeout(context.Background(), stopCleanupOperationTimeout)
+		defer stopCleanupCtxCancel()
+
+		err := o.scyllaClient.StopCleanup(stopCleanupCtx, o.NodeAddress)
+		if err != nil {
+			klog.Warningf("Failed to stop the cleanup: %s", err)
```
Comment (tnozicka) [inline pkg/cmd/operator/cleanupjob.go:146]: nit: as the error will get logged as klog error, do we need the warning as well?

File: pkg/cmd/operator/cleanupjob.go [hunk 6]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
 
+	var errs []error
+
+	err := o.runCleanup(ctx)
+	if err != nil {
+		errs = append(errs, fmt.Errorf("can't run the cleanup: %w", err))
+	}
+
+	select {
+	case <-stopCh:
```
Comment (tnozicka) [inline pkg/cmd/operator/cleanupjob.go:139]: Might be more future proof to use `ctx.Done()` as that's the one that runCleanup uses and someone might say wrap it with a timeout in the future.

File: pkg/cmd/operator/cleanupjob.go [hunk 7]
```diff
@@ -118,11 +122,42 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+
 	go func() {
 		<-stopCh
 		cancel()
 	}()
 
+	var errs []error
+
+	err := o.runCleanup(ctx)
+	if err != nil {
```
Comment (tnozicka) [inline pkg/cmd/operator/cleanupjob.go:134]: let's log that the cleanup call has finished so the logs give you context and timestamps

**Review by tnozicka — COMMENTED** [review]
> In case when Cleanup Job needs to be recreated by the Operator, the new Job could complain about that it cannot execute cleanup operation, because there's already one running.

What if the stop operation fails? (It's not retried, it may fail or the pod may terminate ungracefully.)
Is there an option to stop the old one when the new one is starting?

File: pkg/cmd/operator/cleanupjob.go (hunk 6 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:139]: This is intentional, there shouldn't be any cleanups running when runCleanup ends without an error. It would be ambigous if users would see that cleanups ongoing are stopped just before jobs ends. So I stop it only when stop signal comes.
Lets handle future code changes when they happen.

File: pkg/cmd/operator/cleanupjob.go (hunk 7 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:134]: done

File: pkg/cmd/operator/cleanupjob.go (hunk 5 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:146]: yep, removed

File: pkg/cmd/operator/cleanupjob.go (hunk 6 above)
Comment (tnozicka) [reply pkg/cmd/operator/cleanupjob.go:142]: anyways, should it check the error is not nil? it can happen that the stop channel gets hit after the cleanup exits successfully

Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:142]: added

Comment (tnozicka) [reply pkg/cmd/operator/cleanupjob.go:142]: could just be an else branch but this works for me, thx

**Comment by tnozicka** [comment]
> What if the stop operation fails? (It's not retried, it may fail or the pod may terminate ungracefully.)
Is there an option to stop the old one when the new one is starting?

@zimnx shouldn't the cancelation be retried with some backoff or better retried on next job start?

**Comment by zimnx** [comment]
>  shouldn't the cancellation be retried with some backoff

There's 1s backoff.

>  better retried on next job start?

Any argument behind why retrying on next job start would be better?

**Comment by tnozicka** [comment]
> There's 1s backoff.

ok, I see there is now a backoff for 10s, thx

> Any argument behind why retrying on next job start would be better?

not better, but in addition to cancellation on termination

- pods may terminate ungracefully, cleanup won't be stopped at all
- cleanup cancellation may fail and we can't afford to retry it forever because of terminationGracePeriod. Eventually, there is always a case where this could fail to cancel and something should likely handle it.

> the new Job could complain about that it cannot execute cleanup operation, because there's already one running.

What exactly happens if the cancellation fails and a new job tries to start another cleanup while the old one is running? Is it just a warning, stuck until completion or the new one fails?

**Comment by zimnx** [comment]
> What exactly happens if the cancellation fails and a new job tries to start another cleanup while the old one is running? Is it just a warning, stuck until completion or the new one fails?

```
ERROR 2023-08-21 09:26:15,917 [shard 0] api - Failed force_keyspace_cleanup of system_schema.table{name=columns, id=24101c25-a2ae-3af7-87c1-b40ee1aca33f}: std::runtime_error (cleanup request failed: there is an ongoing cleanup on system_schema.columns)
```
Which fails the request that triggers it. Job would be restarted - Job RestartPolicy is set to OnFailure - attempt to stop would be sent, if unsuccessful Job would spin until this "unstoppable" cleanup would finish, eventually triggering new one. In case when stop would be successful, new one should be triggered right after.

---
> in addition to cancellation on termination

That would solve the ungraceful shutdown, I'll add it.

File: pkg/cmd/operator/cleanupjob.go [hunk 8]
```diff
@@ -118,11 +123,57 @@ func (o *CleanupJobOptions) Run(streams genericclioptions.IOStreams, cmd *cobra.
...
+		return fmt.Errorf("can't clean up: %w", err)
+	}
+
+	return nil
+}
+
+func (o *CleanupJobOptions) runCleanup(ctx context.Context) error {
+	klog.InfoS("Stopping any ongoing cleanup")
+	err := o.scyllaClient.StopCleanup(ctx, o.NodeAddress)
```
Comment (tnozicka) [inline pkg/cmd/operator/cleanupjob.go:172]: just to make sure: if there are no existing cleanups in progress, does this still return nil?

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

/hold
(for https://github.com/scylladb/scylla-operator/pull/1345/files#r1304437045)

**Comment by tnozicka** [comment]
thanks for the updates - one pending question, feel free to `/hold cancel` if that's confirmed

File: pkg/cmd/operator/cleanupjob.go (hunk 8 above)
Comment (zimnx) [reply pkg/cmd/operator/cleanupjob.go:172]: yes:
```
root@basic-us-east-1-us-east-1a-0:/# curl -v -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://127.0.0.1:10000/compaction_manager/stop_compaction?type=CLEANUP'
*   Trying 127.0.0.1:10000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 10000 (#0)
> POST /compaction_manager/stop_compaction?type=CLEANUP HTTP/1.1
> Host: 127.0.0.1:10000
> User-Agent: curl/7.68.0
> Content-Type: application/json
> Accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: application/json
< Date: Thu, 24 Aug 2023 20:04:28 GMT
< Server: Seastar httpd
< 
* Connection #0 to host 127.0.0.1 left intact
```
