### PR TITLE
Fix flakiness of cleanup E2E test

### LINKED ISSUE #1525: Flake: ScyllaCluster [It] nodes are cleaned up after horizontal scaling
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1524/pull-scylla-operator-e2e-gke-parallel/1720397617084502016#1:test-build-log.txt%3A1594
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1524/pull-scylla-operator-e2e-gke-parallel/1720397617084502016/

```console
• [FAILED] [771.623 seconds]
ScyllaCluster [It] nodes are cleaned up after horizontal scaling
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:29
...
[FAILED] Expected
      <[]utils.ObserverEvent[*k8s.io/api/batch/v1.Job] | len:3, cap:15>: [
...
      ]
  to have length 2
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:109 @ 11/03/23 11:31:40.032
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func2.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:109 +0xd45
```

/kind flake
/priority important-longterm

### PR DESCRIPTION
**Pull request by zimnx**
Cleanup token hash annotation is reconciled from the sidecar via polling method. If ring annotation is updated slower than new node joins/decommisions then cleanup job can be triggered twice. This is expected, so e2e test shouldn't fail in such case.

Test logic was aligned to accept extra cleanup job for stale token ring hash, by filtering observed jobs to get only those related to current token ring.

Fixes #1525

### CODE REVIEW

File: test/e2e/set/scyllacluster/scyllacluster_cleanup.go [hunk 1]
```diff
@@ -96,14 +96,20 @@ var _ = g.Describe("ScyllaCluster", func() {
 
 		o.Expect(jobEvents).NotTo(o.BeEmpty())
 
+		tokenRingHash, err := utils.GetCurrentTokenRingHash(ctx, f.KubeClient().CoreV1(), sc)
+		o.Expect(err).NotTo(o.HaveOccurred())
+		framework.Infof("Current token ring hash is %q", tokenRingHash)
```
Comment (rzetelskik) [inline test/e2e/set/scyllacluster/scyllacluster_cleanup.go:101]: Why is this a valuable information? Should I be able to compare it with something? Or know if it's not the expected one?

**Review by rzetelskik — COMMENTED** [review]
one comment, otherwise lgtm

File: test/e2e/set/scyllacluster/scyllacluster_cleanup.go (hunk 1 above)
Comment (zimnx) [reply test/e2e/set/scyllacluster/scyllacluster_cleanup.go:101]: Each cleanup Job has ring hash annotation, the one Operator noticed and created a Job for. Annotations in artifacts should be the same as one printed here. In case of a failure, we can verify if job was stale or not.

**Review by tnozicka — APPROVED** [review]
/approve
lgtm

**Review by rzetelskik — APPROVED** [review]
/lgtm
