### PR TITLE
Extend ScyllaCluster rollout timeout in E2E

### LINKED ISSUE #1232: Flake: ScyllaCluster [It] should re-bootstrap from old PVCs
https://github.com/scylladb/scylla-operator/actions/runs/4885577292/jobs/8729441531?pr=1230
[e2e-artifacts-parallel-alpha.tar.lz4.zip](https://github.com/scylladb/scylla-operator/files/11404414/e2e-artifacts-parallel-alpha.tar.lz4.zip)
[logs_13091.zip](https://github.com/scylladb/scylla-operator/files/11404415/logs_13091.zip)

```
[FAILED] [962.790 seconds]
ScyllaCluster [It] should re-bootstrap from old PVCs
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go:25

  Timeline >>
  STEP: Creating a new namespace @ 05/05/23 05:26:05.603
  May  5 05:26:05.661: INFO: Created namespace "e2e-test-scyllacluster-ddrmd-xnv8b".
  STEP: Waiting for service account token Secret "e2e-user-token" in namespace "e2e-test-scyllacluster-ddrmd-xnv8b". @ 05/05/23 05:26:05.789
  STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-ddrmd-xnv8b". @ 05/05/23 05:26:05.843
  STEP: Creating a ScyllaCluster @ 05/05/23 05:26:05.908
  STEP: Waiting for the ScyllaCluster to rollout (RV=2008) @ 05/05/23 05:26:05.975
  May  5 05:34:18.520: INFO: ScyllaCluster e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf (RV=7328) is rolled out
  STEP: Verifying the ScyllaCluster @ 05/05/23 05:34:23.762
  May  5 05:34:27.013: INFO: Found 3 pvc(s) in namespace "e2e-test-scyllacluster-ddrmd-xnv8b"
  May  5 05:34:27.060: INFO: Found 3 pvc(s) for ScyllaCluster "e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf"
  STEP: Waiting for the ScyllaCluster to reach consistency ALL @ 05/05/23 05:34:27.915
  May  5 05:34:29.278: INFO: ScyllaDB nodes have reached status consistency.
  STEP: Inserting data @ 05/05/23 05:34:29.278
  May  5 05:34:29.313: INFO: Creating CQL session (hosts="10.96.219.96, 10.97.169.180, 10.110.129.105")
  May  5 05:34:30.044: INFO: Creating keyspace "pfpxncsf" with RF 3
  May  5 05:34:31.897: INFO: Creating table "pfpxncsf"."test"
  [FAILED] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:279 @ 05/05/23 05:34:34.926
  STEP: Collecting events from namespace "e2e-test-scyllacluster-ddrmd-xnv8b". @ 05/05/23 05:34:34.964
  STEP: Found 66 events. @ 05/05/23 05:34:35.32
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:06 +0000 UTC - event for basic-gzkkf-auth-token: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-auth-token created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:06 +0000 UTC - event for basic-gzkkf-member: {scyllacluster-controller } ServiceAccountCreated: ServiceAccount e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-member created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:06 +0000 UTC - event for basic-gzkkf-member: {scyllacluster-controller } RoleBindingCreated: RoleBinding e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-member created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:37 +0000 UTC - event for basic-gzkkf-local-client-ca: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-client-ca created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:37 +0000 UTC - event for basic-gzkkf-local-client-ca: {scyllacluster-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-client-ca created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:47 +0000 UTC - event for basic-gzkkf-local-user-admin: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-user-admin created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:59 +0000 UTC - event for basic-gzkkf-local-serving-ca: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-serving-ca created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:26:59 +0000 UTC - event for basic-gzkkf-local-serving-ca: {scyllacluster-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-serving-ca created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:15 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {scyllacluster-controller } StatefulSetCreated: StatefulSet e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:15 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-gzkkf-us-east-1-us-east-1a-0 Pod basic-gzkkf-us-east-1-us-east-1a-0 in StatefulSet basic-gzkkf-us-east-1-us-east-1a success
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:15 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-gzkkf-us-east-1-us-east-1a-0 in StatefulSet basic-gzkkf-us-east-1-us-east-1a successful
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:15 +0000 UTC - event for data-basic-gzkkf-us-east-1-us-east-1a-0: {persistentvolume-controller } WaitForFirstConsumer: waiting for first consumer to be created before binding
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:16 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} FailedMount: MountVolume.SetUp failed for volume "scylladb-serving-certs" : secret "basic-gzkkf-local-serving-certs" not found
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:16 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-0 to fv-az339-828
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:16 +0000 UTC - event for nodeconfig-podinfo-7d53f988-5448-4db2-8fb7-03155cd391b4: {NodeConfigCM-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-7d53f988-5448-4db2-8fb7-03155cd391b4 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:25 +0000 UTC - event for basic-gzkkf-client: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-client created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:25 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-0 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:26 +0000 UTC - event for basic-gzkkf: {scyllacluster-controller } PodDisruptionBudgetCreated: PodDisruptionBudget e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:26 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-1 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:26 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-2 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:32 +0000 UTC - event for basic-gzkkf-local-cql-connection-configs-admin: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-cql-connection-configs-admin created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:32 +0000 UTC - event for basic-gzkkf-local-serving-certs: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-local-serving-certs created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:33 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:34 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:34 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:41 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla:5.0.5" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:42 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:43 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:3.0.1" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:43 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:44 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:44 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:46 +0000 UTC - event for nodeconfig-podinfo-7d53f988-5448-4db2-8fb7-03155cd391b4: {NodeConfigCM-controller } ConfigMapUpdated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-7d53f988-5448-4db2-8fb7-03155cd391b4 updated
  May  5 05:34:35.320: INFO: At 2023-05-05 05:27:53 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:23 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-gzkkf-us-east-1-us-east-1a-1 Pod basic-gzkkf-us-east-1-us-east-1a-1 in StatefulSet basic-gzkkf-us-east-1-us-east-1a success
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:23 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-gzkkf-us-east-1-us-east-1a-1 in StatefulSet basic-gzkkf-us-east-1-us-east-1a successful
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:23 +0000 UTC - event for data-basic-gzkkf-us-east-1-us-east-1a-1: {persistentvolume-controller } WaitForFirstConsumer: waiting for first consumer to be created before binding
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:24 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-1 to fv-az339-828
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:24 +0000 UTC - event for nodeconfig-podinfo-82924002-1e97-48de-8937-be9c2bdb63d5: {NodeConfigCM-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-82924002-1e97-48de-8937-be9c2bdb63d5 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:30 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:31 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Created: Created container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:32 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Started: Started container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:28:41 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla:5.0.5" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:29:03 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Created: Created container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:29:04 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:3.0.1" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:29:04 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Started: Started container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:30:11 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Created: Created container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:30:12 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Started: Started container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:30:13 +0000 UTC - event for nodeconfig-podinfo-82924002-1e97-48de-8937-be9c2bdb63d5: {NodeConfigCM-controller } ConfigMapUpdated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-82924002-1e97-48de-8937-be9c2bdb63d5 updated
  May  5 05:34:35.320: INFO: At 2023-05-05 05:30:16 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Unhealthy: Startup probe failed: HTTP probe failed with statuscode: 503
  May  5 05:34:35.320: INFO: At 2023-05-05 05:30:26 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-1: {kubelet fv-az339-828} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:05 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-gzkkf-us-east-1-us-east-1a-2 Pod basic-gzkkf-us-east-1-us-east-1a-2 in StatefulSet basic-gzkkf-us-east-1-us-east-1a success
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:05 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-gzkkf-us-east-1-us-east-1a-2 in StatefulSet basic-gzkkf-us-east-1-us-east-1a successful
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:05 +0000 UTC - event for data-basic-gzkkf-us-east-1-us-east-1a-2: {persistentvolume-controller } WaitForFirstConsumer: waiting for first consumer to be created before binding
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:07 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-ddrmd-xnv8b/basic-gzkkf-us-east-1-us-east-1a-2 to fv-az339-828
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:07 +0000 UTC - event for nodeconfig-podinfo-ba20d097-b1e3-4a88-bb6a-c3ee5b99e031: {NodeConfigCM-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-ba20d097-b1e3-4a88-bb6a-c3ee5b99e031 created
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:08 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:09 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Created: Created container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:09 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Started: Started container sidecar-injection
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:20 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla:5.0.5" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:21 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Started: Started container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:21 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Started: Started container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:21 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Created: Created container scylla-manager-agent
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:21 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:3.0.1" already present on machine
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:21 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Created: Created container scylla
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:22 +0000 UTC - event for nodeconfig-podinfo-ba20d097-b1e3-4a88-bb6a-c3ee5b99e031: {NodeConfigCM-controller } ConfigMapUpdated: ConfigMap e2e-test-scyllacluster-ddrmd-xnv8b/nodeconfig-podinfo-ba20d097-b1e3-4a88-bb6a-c3ee5b99e031 updated
  May  5 05:34:35.320: INFO: At 2023-05-05 05:32:28 +0000 UTC - event for basic-gzkkf-us-east-1-us-east-1a-2: {kubelet fv-az339-828} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
  STEP: Collecting dumps from namespace "e2e-test-scyllacluster-ddrmd-xnv8b". @ 05/05/23 05:34:35.32
  STEP: Destroying namespace "e2e-test-scyllacluster-ddrmd-xnv8b". @ 05/05/23 05:35:01.594
  STEP: Waiting for namespace "e2e-test-scyllacluster-ddrmd-xnv8b" to be removed. @ 05/05/23 05:35:01.601
  << Timeline

  [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc0004c6f60>: {
          msg: "can't create table: gocql: no response received from cassandra within timeout period",
          err: <*errors.errorString | 0xc000059d30>{
              s: "gocql: no response received from cassandra within timeout period",
          },
      }
      can't create table: gocql: no response received from cassandra within timeout period
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:279 @ 05/05/23 05:34:34.926

  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.insertAndVerifyCQLData({0x2027c40, 0xc00001f1a0}, {0xc0004c87c0, 0x3, 0x4})
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:279 +0xd8
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func6.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go:49 +0x4a5
```

### PR DESCRIPTION
**Pull request by zimnx**
Rollout timeout didn't take into account time required to schedule and complete cleanup Jobs.

Resolves #1232

### CODE REVIEW

File: test/e2e/utils/helpers.go [hunk 1]
```diff
@@ -116,7 +116,7 @@ func IsNodeConfigDoneWithNodeTuningFunc(nodes []*corev1.Node) func(nc *scyllav1a
 }
 
 func RolloutTimeoutForScyllaCluster(sc *scyllav1.ScyllaCluster) time.Duration {
-	return SyncTimeout + time.Duration(GetMemberCount(sc))*memberRolloutTimeout
+	return SyncTimeout + time.Duration(GetMemberCount(sc))*memberRolloutTimeout + cleanupJobTimeout
```
Comment (rzetelskik) [inline test/e2e/utils/helpers.go:119]: shouldn't `cleanupJobTimeout` be added to the `memberRolloutTimeout`?

Comment (zimnx) [reply test/e2e/utils/helpers.go:119]: no, as cleanup jobs are run in parallel after all nodes are rolled out

**Comment by rzetelskik** [comment]
lgtm, thanks
/assign tnozicka

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm
