### PR TITLE
Use Scylla Manager cluster labels for cluster reconciliation

### LINKED ISSUE #1902: Manager controller recreates clusters when manager cluster ID is missing from status
### What happened?

Currently, the manager cluster ID is saved in ScyllaCluster's status on cluster creation. If the controller fails to update ScyllaCluster's status, the ID is lost, or an older generation of the object is reconciled, the controller will delete the existing cluster from the manager state and create it again.

The issue and its root cause are similar https://github.com/scylladb/scylla-operator/issues/1752.

This not only adds a superfluous workload, but may introduce incorrectness, involving e.g. task retention.

/priority important-soon
/assign

### What did you expect to happen?

Clusters in manager state should not be deleted once they've been created successfully.

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Scylla Operator version

master

### Kubernetes platform name and version

n/a

### Please attach the must-gather archive.

n/a

### Anything else we need to know?

Unfortunately, we now have no reliable way of telling whether a cluster existing in manager state corresponds to a K8S object if we don't have the ID.
This should be easy to fix with https://github.com/scylladb/scylla-manager/issues/3219, since we'll be able to save metadata in manager state, and so we'll be able to "reclaim" the cluster despite not having its ID.

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** Currently, when the manager controller fails to save manager's cluster ID in ScyllaCluster's status after cluster's registration with manager, the cluster is deleted and recreated again. As update conflicts are not a rare occurrence, this often causes many unnecessary recreation attempts.
To make the reconciliation more robust, this PR changes this behaviour. Instead of using the ID from status, labels from manager state are used. A cluster is created with a label holding the owner's UID, which allows us to maintain and recognize cluster's identity without relying on the status of our API resources. In turn clusters are only deleted when the owner UID labels is not matching the UID of the current owner, in order to avoid name collisions.

The labels are also extended with a managed hash label to align the cluster update logic with changes recently introduced in https://github.com/scylladb/scylla-operator/pull/2142.

The logic related to creating "actions" is modified to produce one cluster-related action at once and requeue in order to only schedule any further actions on next iteration. The reasoning behind it is to try avoiding errors related to task actions in case of a required cluster action, e.g. when auth token needs to be updated first.

Additionally, the manager state computed in each reconciliation loop is reduced to only one cluster, since cluster names in manager are unique and propagating additional clusters to the state is redundant.

Unit tests are also extended to cover these scenarios and unified for consistency.

**Which issue is resolved by this Pull Request:**
Resolves #1902 

/kind bug
/priority important-soon
/cc

### CODE REVIEW

File: pkg/controller/manager/sync.go [hunk 1]
```diff
@@ -24,59 +25,78 @@ func (c *Controller) getAuthToken(sc *scyllav1.ScyllaCluster) (string, error) {
...
+		// Cluster names in manager state are unique, so it suffices to only find one with a matching name.
+		if mc.Name == clusterName {
+			managerCluster = mc
+			break
 		}
+	}
+
+	if managerCluster == nil {
+		return &managerClusterState{}, nil
+	}
```
Comment (zimnx) [inline pkg/controller/manager/sync.go:46]: could be replace with slices.Find which would be much shorter

File: pkg/controller/manager/sync_test.go [hunk 2]
```diff
@@ -4,675 +4,829 @@ package manager
...
 		},
 	}
 
-	for _, test := range tcs {
-		t.Run(test.Name, func(t *testing.T) {
+	for _, tc := range tt {
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+
 			ctx := context.Background()
```
Comment (zimnx) [inline pkg/controller/manager/sync_test.go:811]: nit: add sane timeout

Comment (rzetelskik) [reply pkg/controller/manager/sync_test.go:811]: nothing in this function consumes the context, it's just legacy, so I'd be leaning towards removing the param if anyhing - wdyt?

File: pkg/controller/manager/sync.go (hunk 1 above)
Comment (rzetelskik) [reply pkg/controller/manager/sync.go]: good point, fixed

File: pkg/controller/manager/status.go [hunk 3]
```diff
@@ -6,30 +6,41 @@ import (
...
 
-func (c *Controller) calculateStatus(sc *scyllav1.ScyllaCluster, managerState *state) *scyllav1.ScyllaClusterStatus {
+func (c *Controller) calculateStatus(sc *scyllav1.ScyllaCluster, state *managerClusterState) *scyllav1.ScyllaClusterStatus {
 	status := sc.Status.DeepCopy()
 
+	status.ManagerID = pointer.Ptr("")
+	status.Backups = []scyllav1.BackupTaskStatus{}
+	status.Repairs = []scyllav1.RepairTaskStatus{}
+
+	if state.Cluster == nil || state.Cluster.Labels[naming.OwnerUIDLabel] != string(sc.UID) {
```
Comment (tnozicka) [inline pkg/controller/manager/status.go:23]: should we report an error or warning when the label is missing? (globally)

**Review by tnozicka — APPROVED** [review]
/approve

/assign @zimnx

File: pkg/controller/manager/sync_test.go (hunk 2 above)
Comment (zimnx) [reply pkg/controller/manager/sync_test.go:811]: I would be against removing context parameter, it's useful once its has its user and having it is recommended practice. I'm fine not touching the timeout too.

File: pkg/controller/manager/status.go (hunk 3 above)
Comment (tnozicka) [reply pkg/controller/manager/status.go]: I mean it more to distinguish between the label being there (lookup in the map), before it's compared with the sc.UID, so you have the distinction in the logs between UID mismatch and `state.cluster.Labels` not having it.

Comment (rzetelskik) [reply pkg/controller/manager/status.go]: I see. Changed to warning on missing label and comment/debug log on mismatch.

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	[cf03afe](https://github.com/scylladb/scylla-operator/commit/cf03afe3d9aefa9a13f710ac220a551fd3887ba2)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2156/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1846873675131785216)	true	`/test e2e-gke-parallel-clusterip`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2156). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

cluster provisioning failed
/retest

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	[cf03afe](https://github.com/scylladb/scylla-operator/commit/cf03afe3d9aefa9a13f710ac220a551fd3887ba2)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2156/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1846888608951177216)	true	`/test e2e-gke-parallel-clusterip`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2156). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

tls test flake, can't possibly be related?
https://github.com/scylladb/scylla-operator/issues/2096#issuecomment-2425801644
/retest

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	[cf03afe](https://github.com/scylladb/scylla-operator/commit/cf03afe3d9aefa9a13f710ac220a551fd3887ba2)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2156/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1848259917215961088)	true	`/test e2e-gke-parallel-clusterip`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2156). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

/test images
/retest
