### PR TITLE
Fix waiting for waitGroup in ScyllaCluster Orphaned PV e2e test

### LINKED ISSUE #1390: Failing test: ScyllaCluster Orphaned PV controller [It] should replace a node with orphaned PV
**Describe the bug**
`ScyllaCluster Orphaned PV controller [It] should replace a node with orphaned PV` is consistently failing on master.
See e.g. https://github.com/scylladb/scylla-operator/actions/runs/6139960919 for details:

```
• [TIMEDOUT] [6136.012 seconds]
ScyllaCluster Orphaned PV controller [It] should replace a node with orphaned PV
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75
  ...
  [FAILED] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:347 @ 09/11/23 00:57:38.987
  ...
  Attempt #2 Failed.  Retrying ↺ @ 09/11/23 00:57:56.38
  ...
  [TIMEDOUT] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75 @ 09/11/23 01:07:06.243
  ...
  Attempt #3 Failed.  Retrying ↺ @ 09/11/23 01:07:23.729
  ...
  [TIMEDOUT] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75 @ 09/11/23 01:07:53.792
  ...
  Attempt #4 Failed.  Retrying ↺ @ 09/11/23 01:08:09.83
  ...
  [TIMEDOUT] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75 @ 09/11/23 01:08:39.88
  ...
  Attempt #5 Failed.  Retrying ↺ @ 09/11/23 01:08:55.997
  ...
  [TIMEDOUT] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75 @ 09/11/23 01:09:26.046
  ...
  [TIMEDOUT] A grace period timeout occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75 @ 09/11/23 01:09:26.046

  Full Stack Trace

  This is the Progress Report generated when the grace period timeout occurred:
    ScyllaCluster Orphaned PV controller should replace a node with orphaned PV (Spec Runtime: 1h42m4.996s)
      github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75
      In [It] (Node Runtime: 30.001s)
        github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:75
        At [By Step] Waiting for the ScyllaCluster to rollout (RV=34403) (Step Runtime: 29.984s)
          github.com/scylladb/scylla-operator/test/e2e/framework/log.go:45
          ...
  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------
SSSS
------------------------------
[ReportAfterSuite] [FAILED] [0.000 seconds]
[ReportAfterSuite] Autogenerated ReportAfterSuite for --json-report --junit-report
autogenerated by Ginkgo

  [FAILED] Test Report unavailable because a Ginkgo parallel process disappeared
    The aggregated report could not be fetched for a ReportAfterSuite node.  A
    Ginkgo parallel process disappeared before it could finish reporting.

  
  In [ReportAfterSuite] at: autogenerated by Ginkgo @ 09/11/23 01:09:37.112

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:**
Currently, when an error occurs in `ScyllaCluster Orphaned PV controller [It] should replace a node with orphaned PV` E2E test, the test hangs indefinitely, waiting for waitGroup, because of the order of deferred functions. This PR fixes it by reordering the deferred functions.

**Which issue is resolved by this Pull Request:**
Resolves #1390

### CODE REVIEW

File: test/e2e/set/scyllacluster/scyllacluster_pv.go [hunk 1]
```diff
@@ -99,10 +116,7 @@ var _ = g.Describe("ScyllaCluster Orphaned PV controller", func() {
 		// ScyllaCluster is going to request a PVC from that StorageClass, and the test is going to request a clone of the original PVC
 		// from the default StorageClass to get any storage. Then the bound PV is rebounded to the original PVC
 		// but with empty NodeAffinity. This allows the test to trigger the orphaned PV cleanup logic.
-		provisionerCtx, provisionerCancel := context.WithCancel(ctx)
-		defer provisionerCancel()
 
-		var wg sync.WaitGroup
 		wg.Add(1)
```
Comment (zimnx) [inline test/e2e/set/scyllacluster/scyllacluster_pv.go:120]: Why not swapping context creation and sync.WaitGroup? Context is created prematurely, and defer with Wait is in wrong place too.
Like this:
```
		var wg sync.WaitGroup
		defer wg.Wait()

		provisionerCtx, provisionerCancel := context.WithCancel(ctx)
		defer provisionerCancel()
		wg.Add(1)
		go func() {
			defer wg.Done()
```

Comment (rzetelskik) [reply test/e2e/set/scyllacluster/scyllacluster_pv.go:108]: I don't mind - it seems a little cleaner. Changed.

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by zimnx** [comment]
PR description is stale, please update it.
