### PR TITLE
 Extend RackStatus API with UpdatedMembers and Stale fields

### LINKED ISSUE #624: e2e flake: agent requires authentication
https://github.com/scylladb/scylla-operator/runs/2759361432?check_suite_focus=true#step:11:341

https://github.com/scylladb/scylla-operator/commit/984db5d684fe3c1eb44369dc572a15558008552f

```
• Failure [109.585 seconds]
ScyllaCluster authentication
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_auth.go:24
  agent requires authentication [It]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_auth.go:29

  Unexpected error:
      <*errors.withStack | 0xc0004e7aa0>: {
          error: {
              cause: {
                  _statusCode: 401,
                  Payload: {
                      Code: 401,
                      Message: "unauthorized",
                  },
              },
              msg: "giving up after 1 attempts",
          },
          stack: [0x1644646, 0x1644471, 0x163a1d3, 0x16422e5, 0x164c02e, 0x1651b8d, 0x12b6a03, 0x12b661c, 0x12b5be7, 0x12b9aef, 0x12b9192, 0x12e1e91, 0x12e19a7, 0x12e1197, 0x12e38a6, 0x12f0158, 0x12efead, 0x16593ec, 0x16590b7, 0x165991d, 0x14f1812, 0x14f2395, 0x1659d5d, 0x1659d54, 0x4397f6, 0x46d701],
      }
      giving up after 1 attempts: agent [HTTP 401] unauthorized
  occurred

  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_auth.go:144

  Full Stack Trace
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func1.1()
  	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_auth.go:144 +0x1f88
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0004b41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:113 +0xa3
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0004b41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:64 +0x15c
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0007d81e0, 0x1b7b880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/it_node.go:26 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000266870, 0x0, 0x1b7b880, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:215 +0x72f
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000266870, 0x1b7b880, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:138 +0xf2
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0000d4160, 0xc000266870, 0x0)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:200 +0x111
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0000d4160, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:170 +0x147
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0000d4160, 0xc00064cee0)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:66 +0x117
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002ed490, 0x7fc48d9b6590, 0x26f2c00, 0x198f5b9, 0x19, 0xc0007d8020, 0x2, 0x2, 0x1bb7478, 0xc0002c9400, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/suite/suite.go:79 +0x546
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1b7b920, 0x26f2c00, 0x198f5b9, 0x19, 0xc0007d8000, 0x2, 0x2, 0x2)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:229 +0x218
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x1b7b920, 0x26f2c00, 0x198f5b9, 0x19, 0xc00066a010, 0x1, 0x1, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:217 +0xad
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).run(0xc0005c60e0, 0x1bafd78, 0xc0000a0040, 0x1b7cb00, 0xc0000b2000, 0x1b7cb20, 0xc0000b2008, 0x1b7cb20, 0xc0000b2010, 0x1, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:196 +0x24c
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).Run(0xc0005c60e0, 0x1b7cb00, 0xc0000b2000, 0x1b7cb20, 0xc0000b2008, 0x1b7cb20, 0xc0000b2010, 0x1972e52, 0x3, 0x0, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:149 +0x357
  github.com/scylladb/scylla-operator/pkg/cmd/tests.NewRunCommand.func1(0xc000464840, 0xc0007c8130, 0x0, 0x1, 0x0, 0x0)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:81 +0xfd
  github.com/spf13/cobra.(*Command).execute(0xc000464840, 0xc0007c8120, 0x1, 0x1, 0xc000464840, 0xc0007c8120)
  	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
  github.com/spf13/cobra.(*Command).ExecuteC(0xc000464580, 0xc0000b2000, 0x1b7cb20, 0xc0000b2008)
  	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.1.1/command.go:895
  main.main()
  	github.com/scylladb/scylla-operator/cmd/scylla-operator-tests/scylla-operator-tests.go:37 +0x23d
------------------------------
```

### LINKED ISSUE #638: Flaky e2e test - should support scaling
```
• Failure [59.919 seconds]
ScyllaCluster 
  should support scaling
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_scaling.go:21
[BeforeEach] ScyllaCluster
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:56
Jun 13 23:46:01.505: STEP: Creating a new namespace
Jun 13 23:46:01.512: INFO: Created namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
Jun 13 23:46:01.546: STEP: Waiting for ServiceAccount "e2e-user" in namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
Jun 13 23:46:01.556: STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
[It] should support scaling
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_scaling.go:21
Jun 13 23:46:01.559: STEP: Creating a ScyllaCluster with 1 member
Jun 13 23:46:01.592: STEP: Waiting for the ScyllaCluster to rollout
Jun 13 23:46:44.935: STEP: Scaling the ScyllaCluster to 2 replicas
Jun 13 23:46:44.956: STEP: Waiting for the ScyllaCluster to rollout
Jun 13 23:46:44.965: STEP: Verifying the ScyllaCluster
Jun 13 23:46:45.134: STEP: Scaling the ScyllaCluster back to 1 replica
Jun 13 23:46:45.154: STEP: Waiting for the ScyllaCluster to rollout
Jun 13 23:46:45.158: STEP: Verifying the ScyllaCluster
[AfterEach] ScyllaCluster
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:57
Jun 13 23:46:45.164: STEP: Collecting events from namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
Jun 13 23:46:45.171: STEP: Found 28 events.
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic: {scylla-cluster-controller } Synced: Rack us-east-1a scaled up to 1 members
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic: {scylla-cluster-controller } Synced: Rack us-east-1a created
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic: {scylla-cluster-controller } PodDisruptionBudgetCreated: e2e-test-scyllacluster-xrbl6-xz6tl/basic Created
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic: {controllermanager } NoPods: No matching pods found
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic-auth-token: {scylla-cluster-controller } SecretCreated: e2e-test-scyllacluster-xrbl6-xz6tl/basic-auth-token Created
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-us-east-1-us-east-1a-0 in StatefulSet basic-us-east-1-us-east-1a successful
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-us-east-1-us-east-1a-0 Pod basic-us-east-1-us-east-1a-0 in StatefulSet basic-us-east-1-us-east-1a success
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {default-scheduler } FailedScheduling: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {k8s.io/minikube-hostpath_fv-az210-370_796c6c6c-df42-41f1-8c43-3cf0d8d175dc } Provisioning: External provisioner is provisioning volume for claim "e2e-test-scyllacluster-xrbl6-xz6tl/data-basic-us-east-1-us-east-1a-0"
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:01 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {k8s.io/minikube-hostpath_fv-az210-370_796c6c6c-df42-41f1-8c43-3cf0d8d175dc } ProvisioningSucceeded: Successfully provisioned volume pvc-6e5affee-b85d-40fd-9da4-7b75e63696a4
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:03 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-xrbl6-xz6tl/basic-us-east-1-us-east-1a-0 to fv-az210-370
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:04 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:04 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Created: Created container sidecar-injection
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:04 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Started: Started container sidecar-injection
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Pulled: Container image "docker.io/scylladb/scylla:4.4.2" already present on machine
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Created: Created container scylla
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Started: Started container scylla-manager-agent
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Created: Created container scylla-manager-agent
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:2.3.0" already present on machine
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:05 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Started: Started container scylla
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:14 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-370} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for basic: {scylla-cluster-controller } Synced: Rack us-east-1a scaled up to 2 members
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-us-east-1-us-east-1a-1 in StatefulSet basic-us-east-1-us-east-1a successful
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-us-east-1-us-east-1a-1 Pod basic-us-east-1-us-east-1a-1 in StatefulSet basic-us-east-1-us-east-1a success
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for basic-us-east-1-us-east-1a-1: {default-scheduler } FailedScheduling: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for data-basic-us-east-1-us-east-1a-1: {k8s.io/minikube-hostpath_fv-az210-370_796c6c6c-df42-41f1-8c43-3cf0d8d175dc } Provisioning: External provisioner is provisioning volume for claim "e2e-test-scyllacluster-xrbl6-xz6tl/data-basic-us-east-1-us-east-1a-1"
Jun 13 23:46:45.171: INFO: At 2021-06-13 23:46:45 +0000 UTC - event for data-basic-us-east-1-us-east-1a-1: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
Jun 13 23:46:45.171: STEP: Collecting dumps from namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
W0613 23:46:45.488586       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Jun 13 23:46:45.531: STEP: Destroying namespace "e2e-test-scyllacluster-xrbl6-xz6tl".
Jun 13 23:46:45.538: STEP: Waiting for namespace "e2e-test-scyllacluster-xrbl6-xz6tl" to be removed.

ScyllaCluster
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_scaling.go:16
  should support scaling [It]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_scaling.go:21

  Expected
      <int32>: 1
  to equal
      <int32>: 2

  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:21

  Full Stack Trace
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.verifyStatefulset(0x1bb7528, 0xc000a36c60, 0xc000301900)
  	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:21 +0x34d
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.verifyScyllaCluster(0x1bb7528, 0xc000a36c60, 0x1bdb678, 0xc000337b80, 0xc000486780)
  	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:46 +0x42d
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func5.1()
  	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_scaling.go:77 +0x122b
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00047bb60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:113 +0xa3
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc00047bb60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:64 +0x15c
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0006acf80, 0x1b82ee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/it_node.go:26 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0006a8b40, 0x0, 0x1b82ee0, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:215 +0x72f
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0006a8b40, 0x1b82ee0, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:138 +0xf2
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc00025c9a0, 0xc0006a8b40, 0x8)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:200 +0x111
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc00025c9a0, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:170 +0x147
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc00025c9a0, 0xc0005e1f40)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:66 +0x117
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002eb5e0, 0x7f0df19e2ec8, 0x26fbc40, 0x1995bbb, 0x19, 0xc0006ac6c0, 0x2, 0x2, 0x1bbebb8, 0xc0002c9400, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/suite/suite.go:79 +0x546
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1b82f80, 0x26fbc40, 0x1995bbb, 0x19, 0xc0006ac6a0, 0x2, 0x2, 0x2)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:229 +0x218
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x1b82f80, 0x26fbc40, 0x1995bbb, 0x19, 0xc0004b8810, 0x1, 0x1, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:217 +0xad
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).run(0xc0005c80e0, 0x1bb74b8, 0xc0000a1680, 0x1b84160, 0xc0000b2000, 0x1b84180, 0xc0000b2008, 0x1b84180, 0xc0000b2010, 0x1, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:196 +0x24c
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).Run(0xc0005c80e0, 0x1b84160, 0xc0000b2000, 0x1b84180, 0xc0000b2008, 0x1b84180, 0xc0000b2010, 0x19793f4, 0x3, 0x0, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:149 +0x357
  github.com/scylladb/scylla-operator/pkg/cmd/tests.NewRunCommand.func1(0xc000128580, 0xc0005aa3e0, 0x0, 0x1, 0x0, 0x0)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:81 +0xfd
  github.com/spf13/cobra.(*Command).execute(0xc000128580, 0xc0005aa3d0, 0x1, 0x1, 0xc000128580, 0xc0005aa3d0)
  	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
  github.com/spf13/cobra.(*Command).ExecuteC(0xc0001282c0, 0xc0000b2000, 0x1b84180, 0xc0000b2008)
  	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.1.1/command.go:895
  main.main()
  	github.com/scylladb/scylla-operator/cmd/scylla-operator-tests/scylla-operator-tests.go:37 +0x23d
------------------------------
```

### LINKED ISSUE #639: Flaky e2e test - orphaned pv
```
ScyllaCluster Orphaned PV 
  should replace a node with orphaned PV
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:25
[BeforeEach] ScyllaCluster Orphaned PV
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:56
Jun 13 23:31:32.163: STEP: Creating a new namespace
Jun 13 23:31:32.172: INFO: Created namespace "e2e-test-scyllacluster-9494v-jx7mk".
Jun 13 23:31:32.188: STEP: Waiting for ServiceAccount "e2e-user" in namespace "e2e-test-scyllacluster-9494v-jx7mk".
Jun 13 23:31:32.203: STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-9494v-jx7mk".
[It] should replace a node with orphaned PV
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:25
Jun 13 23:31:32.206: STEP: Creating a ScyllaCluster
Jun 13 23:31:32.233: STEP: Waiting for the ScyllaCluster to deploy
Jun 13 23:36:02.330: STEP: Verifying the ScyllaCluster
Jun 13 23:36:02.452: STEP: Simulating a PV on node that's gone
Jun 13 23:36:02.506: STEP: Waiting for the PVC to be replaced
Jun 13 23:36:13.715: STEP: Waiting for the ScyllaCluster to deploy
Jun 13 23:36:13.740: STEP: Verifying the ScyllaCluster
[AfterEach] ScyllaCluster Orphaned PV
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:57
Jun 13 23:36:13.917: STEP: Collecting dumps from namespace "e2e-test-scyllacluster-9494v-jx7mk".
Jun 13 23:36:14.337: STEP: Destroying namespace "e2e-test-scyllacluster-9494v-jx7mk".
Jun 13 23:36:14.341: STEP: Waiting for namespace "e2e-test-scyllacluster-9494v-jx7mk" to be removed.

• Failure in Spec Teardown (AfterEach) [309.473 seconds]
ScyllaCluster Orphaned PV
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:20
  should replace a node with orphaned PV [AfterEach]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_pv.go:25

  Unexpected error:
      <*errors.StatusError | 0xc0005a01e0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "container \"scylla\" in pod \"basic-us-east-1-us-east-1a-2\" is waiting to start: PodInitializing",
              Reason: "BadRequest",
              Details: nil,
              Code: 400,
          },
      }
      container "scylla" in pod "basic-us-east-1-us-east-1a-2" is waiting to start: PodInitializing
  occurred

  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:300

  Full Stack Trace
  github.com/scylladb/scylla-operator/test/e2e/framework.(*Framework).afterEach(0xc00003d700)
  	github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:300 +0x585
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00047b620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:113 +0xa3
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc00047b620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:64 +0x15c
  github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc00000ed50, 0x1b82ee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/setup_nodes.go:15 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample.func1(0xc0007d1270, 0xc0006a8690, 0x1b82ee0, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:180 +0x3cd
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0006a8690, 0x0, 0x1b82ee0, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:218 +0x809
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0006a8690, 0x1b82ee0, 0xc0002c9400)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:138 +0xf2
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc00025c9a0, 0xc0006a8690, 0x4)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:200 +0x111
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc00025c9a0, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:170 +0x147
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc00025c9a0, 0xc0005e1f40)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:66 +0x117
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002eb5e0, 0x7f0df19e2ec8, 0x26fbc40, 0x1995bbb, 0x19, 0xc0006ac6c0, 0x2, 0x2, 0x1bbebb8, 0xc0002c9400, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/suite/suite.go:79 +0x546
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1b82f80, 0x26fbc40, 0x1995bbb, 0x19, 0xc0006ac6a0, 0x2, 0x2, 0x2)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:229 +0x218
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x1b82f80, 0x26fbc40, 0x1995bbb, 0x19, 0xc0004b8810, 0x1, 0x1, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:217 +0xad
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).run(0xc0005c80e0, 0x1bb74b8, 0xc0000a1680, 0x1b84160, 0xc0000b2000, 0x1b84180, 0xc0000b2008, 0x1b84180, 0xc0000b2010, 0x1, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:196 +0x24c
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).Run(0xc0005c80e0, 0x1b84160, 0xc0000b2000, 0x1b84180, 0xc0000b2008, 0x1b84180, 0xc0000b2010, 0x19793f4, 0x3, 0x0, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:149 +0x357
  github.com/scylladb/scylla-operator/pkg/cmd/tests.NewRunCommand.func1(0xc000128580, 0xc0005aa3e0, 0x0, 0x1, 0x0, 0x0)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:81 +0xfd
  github.com/spf13/cobra.(*Command).execute(0xc000128580, 0xc0005aa3d0, 0x1, 0x1, 0xc000128580, 0xc0005aa3d0)
  	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
  github.com/spf13/cobra.(*Command).ExecuteC(0xc0001282c0, 0xc0000b2000, 0x1b84180, 0xc0000b2008)
  	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.1.1/command.go:895
  main.main()
  	github.com/scylladb/scylla-operator/cmd/scylla-operator-tests/scylla-operator-tests.go:37 +0x23d

### LINKED ISSUE #660: e2e flake - Scylla Manager integration - should discover cluster and sync tasks
```
------------------------------
Scylla Manager integration 
  should discover cluster and sync tasks
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:22
[BeforeEach] Scylla Manager integration
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:57
Jun 28 20:45:36.075: STEP: Creating a new namespace
Jun 28 20:45:36.082: INFO: Created namespace "e2e-test-scyllacluster-c97pj-c2jqb".
Jun 28 20:45:36.087: STEP: Waiting for ServiceAccount "e2e-user" in namespace "e2e-test-scyllacluster-c97pj-c2jqb".
Jun 28 20:45:36.098: STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-c97pj-c2jqb".
[It] should discover cluster and sync tasks
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:22
Jun 28 20:45:36.100: STEP: Creating a ScyllaCluster
Jun 28 20:45:36.129: STEP: Waiting for the ScyllaCluster to deploy
Jun 28 20:46:17.558: STEP: Verifying the ScyllaCluster
Jun 28 20:46:17.588: STEP: Waiting for the cluster sync with Scylla Manager
[AfterEach] Scylla Manager integration
  github.com/scylladb/scylla-operator/test/e2e/framework/framework.go:58
Jun 28 20:46:51.589: STEP: Collecting events from namespace "e2e-test-scyllacluster-c97pj-c2jqb".
Jun 28 20:46:51.599: STEP: Found 23 events.
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic: {scyllacluster-controller } PodDisruptionBudgetCreated: PodDisruptionBudget e2e-test-scyllacluster-c97pj-c2jqb/basic created
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-auth-token: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-c97pj-c2jqb/basic-auth-token created
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-client: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-c97pj-c2jqb/basic-client created
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-us-east-1-us-east-1a-0 Pod basic-us-east-1-us-east-1a-0 in StatefulSet basic-us-east-1-us-east-1a success
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-us-east-1-us-east-1a: {scyllacluster-controller } StatefulSetCreated: StatefulSet e2e-test-scyllacluster-c97pj-c2jqb/basic-us-east-1-us-east-1a created
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-us-east-1-us-east-1a-0 in StatefulSet basic-us-east-1-us-east-1a successful
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-c97pj-c2jqb/basic-us-east-1-us-east-1a-0 created
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {default-scheduler } FailedScheduling: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {k8s.io/minikube-hostpath_fv-az210-874_9c86d4b1-804b-408c-9cb1-7bfeef08ca2f } Provisioning: External provisioner is provisioning volume for claim "e2e-test-scyllacluster-c97pj-c2jqb/data-basic-us-east-1-us-east-1a-0"
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:36 +0000 UTC - event for data-basic-us-east-1-us-east-1a-0: {k8s.io/minikube-hostpath_fv-az210-874_9c86d4b1-804b-408c-9cb1-7bfeef08ca2f } ProvisioningSucceeded: Successfully provisioned volume pvc-5d9bfd94-3d3b-493c-8914-abf6464a380d
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:38 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-c97pj-c2jqb/basic-us-east-1-us-east-1a-0 to fv-az210-874
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:39 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Started: Started container sidecar-injection
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:39 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Created: Created container sidecar-injection
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:39 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Started: Started container scylla
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Created: Created container scylla
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Pulled: Container image "docker.io/scylladb/scylla:4.4.2" already present on machine
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Created: Created container scylla-manager-agent
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Started: Started container scylla-manager-agent
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:40 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:2.3.0" already present on machine
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:43 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Unhealthy: Startup probe failed: HTTP probe failed with statuscode: 503
Jun 28 20:46:51.599: INFO: At 2021-06-28 20:45:57 +0000 UTC - event for basic-us-east-1-us-east-1a-0: {kubelet fv-az210-874} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
Jun 28 20:46:51.599: STEP: Collecting dumps from namespace "e2e-test-scyllacluster-c97pj-c2jqb".
W0628 20:46:51.752615       1 rest/warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Jun 28 20:46:51.776: STEP: Destroying namespace "e2e-test-scyllacluster-c97pj-c2jqb".
Jun 28 20:46:51.781: STEP: Waiting for namespace "e2e-test-scyllacluster-c97pj-c2jqb" to be removed.
I0628 20:47:18.542700       1 framework/framework.go:244] "Namespace removed." Namespace="e2e-test-scyllacluster-c97pj-c2jqb"

• Failure [102.468 seconds]
Scylla Manager integration
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:17
  should discover cluster and sync tasks [It]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:22

  Unexpected error:
      <*errors.errorString | 0xc0002f6d90>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred

  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:91

  Full Stack Trace
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func8.1()
  	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:91 +0xa91
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0006ed500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:113 +0xa3
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0006ed500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/runner.go:64 +0x15c
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0006e50a0, 0x1c18dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/leafnodes/it_node.go:26 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0002fc690, 0x0, 0x1c18dc0, 0xc000301e80)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:215 +0x72f
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0002fc690, 0x1c18dc0, 0xc000301e80)
  	github.com/onsi/ginkgo@v1.15.0/internal/spec/spec.go:138 +0xf2
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000292c60, 0xc0002fc690, 0x4)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:200 +0x111
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000292c60, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:170 +0x147
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000292c60, 0xc0005eb130)
  	github.com/onsi/ginkgo@v1.15.0/internal/specrunner/spec_runner.go:66 +0x117
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00038dd50, 0x7f8d8d04cea8, 0x27ce530, 0x1a35e91, 0x19, 0xc0006e4020, 0x2, 0x2, 0x1c52258, 0xc000301e80, ...)
  	github.com/onsi/ginkgo@v1.15.0/internal/suite/suite.go:79 +0x546
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1c18e40, 0x27ce530, 0x1a35e91, 0x19, 0xc0006e4000, 0x2, 0x2, 0x2)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:229 +0x218
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x1c18e40, 0x27ce530, 0x1a35e91, 0x19, 0xc000044030, 0x1, 0x1, 0x1)
  	github.com/onsi/ginkgo@v1.15.0/ginkgo_dsl.go:217 +0xad
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).run(0xc000152e00, 0x1c4ae78, 0xc0003d0540, 0x1c19f60, 0xc000130000, 0x1c19f80, 0xc000130008, 0x1c19f80, 0xc000130010, 0x1, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:196 +0x257
  github.com/scylladb/scylla-operator/pkg/cmd/tests.(*RunOptions).Run(0xc000152e00, 0x1c19f60, 0xc000130000, 0x1c19f80, 0xc000130008, 0x1c19f80, 0xc000130010, 0x1a1a6d8, 0x3, 0x0, ...)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:149 +0x357
  github.com/scylladb/scylla-operator/pkg/cmd/tests.NewRunCommand.func1(0xc000236840, 0xc00057ed40, 0x0, 0x1, 0x0, 0x0)
  	github.com/scylladb/scylla-operator/pkg/cmd/tests/tests_run.go:81 +0xfd
  github.com/spf13/cobra.(*Command).execute(0xc000236840, 0xc00057ed30, 0x1, 0x1, 0xc000236840, 0xc00057ed30)
  	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
  github.com/spf13/cobra.(*Command).ExecuteC(0xc000236580, 0xc000130000, 0x1c19f80, 0xc000130008)
  	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.1.1/command.go:895
  main.main()
  	github.com/scylladb/scylla-operator/cmd/scylla-operator-tests/scylla-operator-tests.go:37 +0x23d
```
https://github.com/scylladb/scylla-operator/suites/3106827417/artifacts/71077935

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
UpdatedMembers and Stale field are needed to reliably determine if a ScyllaCluster is rolled out or still Progressing.

**Which issue is resolved by this Pull Request:**
This should fix number of races when we see a ScyllaCluster as rolled out (although it goes back to progressing later on) while the StatefulSet is still progressing.

Resolves #660
Resolves #639
Resolves #638
Resolves #624

### CODE REVIEW

File: pkg/controller/scyllacluster/controller.go [hunk 1]
```diff
@@ -41,6 +41,8 @@ const (
 	// maxSyncDuration enforces preemption. Do not raise the value! Controllers shouldn't actively wait,
 	// but rather use the queue.
 	maxSyncDuration = 30 * time.Second
+
+	artificialDelayForCachesToCatchUp = 10 * time.Second
```
Comment (zimnx) [inline pkg/controller/scyllacluster/controller.go:45]: I think reconcilation of three rack cluster would extend the maxSyncDuration due sleeps. Let's account for these sleeps in sync timeout calculation

Comment (tnozicka) [reply pkg/controller/scyllacluster/controller.go:45]: yep, I'll aggregate then to one in a follow up

File: pkg/controller/scyllacluster/status.go [hunk 2]
```diff
@@ -46,102 +55,88 @@ func (scc *Controller) getScyllaVersion(sc *scyllav1.ScyllaCluster, rack *scylla
...
-		}
+	if sts == nil {
+		return status
+	}
 
-		stsName := naming.StatefulSetNameForRack(rack, sc)
-		rackStatefulSet := statefulSetMap[stsName]
-		if rackStatefulSet == nil {
-			continue
+	// Update Members
```
[the remark this answers is not in the document]
Comment (tnozicka) [reply pkg/controller/scyllacluster/status.go:74]: yeah, didn't like it either but it was preexisting - I'll remove it in a follow up

**Review by zimnx — APPROVED** [review]

File: pkg/controller/scyllacluster/controller.go (hunk 1 above)
Comment (tnozicka) [reply pkg/controller/scyllacluster/controller.go:45]: https://github.com/scylladb/scylla-operator/pull/685

File: pkg/controller/scyllacluster/status.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (tnozicka) [reply pkg/controller/scyllacluster/status.go:74]: https://github.com/scylladb/scylla-operator/pull/685
