### PR TITLE
Return empty list of loop devices when `losetup` doesn't print anything

### LINKED ISSUE #1775: NodeConfig can't create raid device on EKS
### What happened?

NodeConfig trying to create raid device on EKS is stuck due to unsupported output of losetup.

```
E0228 13:44:09.870172       1 nodesetup/controller.go:192] syncing key 'cluster' failed: failed to sync nodeconfig "cluster": can't sync loop devices: can't get node config loop devices: can't list loop devices: failed to unmarshal losetup output "": unexpected end of JSON input
```

### What did you expect to happen?

NodeConfig setting up local disks the way wanted.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy latest scylla-operator, create NodeConfig setting up a raid device.

### Scylla Operator version

latest

### Kubernetes platform name and version

EKS

### Please attach the must-gather archive.

-

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zimnx**
Version of `losetup` installed on EKS has different behavior when there are no loop devices on the node. On GKE and local env, it returns an empty list of loop devices as json output, where on EKS it doesn't print anything, even though we ask for json explicitly.
Losetup library now supports both behaviors.

Fixes #1775

### CODE REVIEW

File: pkg/util/losetup/losetup_test.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+		expectedLoopDevices []*LoopDevice
+		expectedError       error
+	}{
+		{
+			name: "losetup fails with random error",
+			commands: []exectest.Command{
+				{
+					Cmd:    "losetup",
+					Args:   []string{"--all", "--list", "--json"},
+					Stdout: []byte("stdout error"),
```
Comment (tnozicka) [inline pkg/util/losetup/losetup_test.go:30]: tiny nit: i suppose since the error is within stderr, "stdout output" or something like that might be more fitting here

**Review by tnozicka — APPROVED** [review]
/approve
lgtm

File: pkg/util/losetup/losetup_test.go (hunk 1 above)
Comment (zimnx) [reply pkg/util/losetup/losetup_test.go]: done

**Comment by zimnx** [comment]
Flake - https://github.com/scylladb/scylla-operator/issues/1426#issuecomment-1970951498
/retest

**Review by tnozicka — COMMENTED** [review]
/lgtm
thanks
