### PR TITLE
Disable ScyllaDBMonitoring tests in OpenShift E2E

### LINKED ISSUE #2318: E2E Failure [Openshift] - ScyllaDBMonitoring should setup monitoring stack [It] with "Platform" monitoring type
```
 ScyllaDBMonitoring should setup monitoring stack [It] with "Platform" monitoring type
github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:406
  Timeline >>
  STEP: Creating a new namespace @ 01/13/25 06:57:16.798
  Jan 13 06:57:16.854: INFO: Created namespace "e2e-test-scylladbmonitoring-q984l-0-b87rv".
  STEP: Waiting for service account token Secret "e2e-user-token" in namespace "e2e-test-scylladbmonitoring-q984l-0-b87rv". @ 01/13/25 06:57:16.939
  STEP: Waiting for default ServiceAccount in namespace "e2e-test-scylladbmonitoring-q984l-0-b87rv". @ 01/13/25 06:57:17.003
  STEP: Waiting for kube-root-ca.crt in namespace "e2e-test-scylladbmonitoring-q984l-0-b87rv". @ 01/13/25 06:57:17.012
  STEP: Creating a ScyllaCluster with a single node @ 01/13/25 06:57:17.04
  STEP: Creating a ScyllaDBMonitoring @ 01/13/25 06:57:17.217
  STEP: Waiting for the ScyllaCluster to roll out (RV=39682) @ 01/13/25 06:57:17.303
  Jan 13 07:03:34.428: INFO: ScyllaCluster e2e-test-scylladbmonitoring-q984l-0-b87rv/basic-r945t (RV=48840) is rolled out
  STEP: Verifying the ScyllaCluster @ 01/13/25 07:03:34.429
  Jan 13 07:03:34.451: INFO: Found 1 pvc(s) in namespace "e2e-test-scylladbmonitoring-q984l-0-b87rv"
  Jan 13 07:03:34.451: INFO: Found 1 pvc(s) for ScyllaCluster "e2e-test-scylladbmonitoring-q984l-0-b87rv/basic-r945t"
  STEP: Waiting for the ScyllaDBMonitoring to roll out (RV=39721) @ 01/13/25 07:03:34.467
  Jan 13 07:03:34.472: INFO: ScyllaDBMonitoring e2e-test-scylladbmonitoring-q984l-0-b87rv/basic-r945t (RV=48139) is rolled out
  STEP: Verifying that Prometheus is configured correctly @ 01/13/25 07:03:34.473
  Jan 13 07:03:34.483: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:03:35.486: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:03:36.488: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:03:37.491: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0 
[...]
   << Timeline
  [FAILED] Timed out after 300.001s.
  The function passed to Eventually failed at github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:256 with:
  Unexpected error:
      <*url.Error | 0xc000c9a1b0>: 
      Get "https://172.30.183.153:9142/api/v1/targets": EOF
      {
          Op: "Get",
          URL: "https://172.30.183.153:9142/api/v1/targets",
          Err: <*errors.errorString | 0x49bc800>{s: "EOF"},
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:291 @ 01/13/25 07:08:34.481
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring.init.func2.2(0xc00038ebc0)
    	github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:291 +0x1670
    reflect.Value.call({0x1ef9000?, 0xc000735af0?, 0x13?}, {0x2440919, 0x4}, {0xc0006840d8, 0x1, 0x1?})
    	reflect/value.go:581 +0xca6
    reflect.Value.Call({0x1ef9000?, 0xc000735af0?, 0x363d730?}, {0xc0006840d8?, 0x19f0445?, 0x0?})
    	reflect/value.go:365 +0xb9 

```

### LINKED ISSUE #2319: E2E Failure [Openshift] - ScyllaDBMonitoring should setup monitoring stack [It] with "SaaS" monitoring type
```
 ScyllaDBMonitoring should setup monitoring stack [It] with "SaaS" monitoring type
github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:394
  Timeline >>
  STEP: Creating a new namespace @ 01/13/25 06:57:20.005
  Jan 13 06:57:20.043: INFO: Created namespace "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn".
  STEP: Waiting for service account token Secret "e2e-user-token" in namespace "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn". @ 01/13/25 06:57:20.111
  STEP: Waiting for default ServiceAccount in namespace "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn". @ 01/13/25 06:57:20.178
  STEP: Waiting for kube-root-ca.crt in namespace "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn". @ 01/13/25 06:57:20.415
  STEP: Creating a ScyllaCluster with a single node @ 01/13/25 06:57:20.751
  STEP: Creating a ScyllaDBMonitoring @ 01/13/25 06:57:20.785
  STEP: Waiting for the ScyllaCluster to roll out (RV=41085) @ 01/13/25 06:57:20.865
  Jan 13 07:05:04.171: INFO: ScyllaCluster e2e-test-scylladbmonitoring-tcxgl-0-wrtxn/basic-xj4vg (RV=52542) is rolled out
  STEP: Verifying the ScyllaCluster @ 01/13/25 07:05:04.172
  Jan 13 07:05:04.273: INFO: Found 1 pvc(s) in namespace "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn"
  Jan 13 07:05:04.279: INFO: Found 1 pvc(s) for ScyllaCluster "e2e-test-scylladbmonitoring-tcxgl-0-wrtxn/basic-xj4vg"
  STEP: Waiting for the ScyllaDBMonitoring to roll out (RV=41088) @ 01/13/25 07:05:04.404
  Jan 13 07:05:04.460: INFO: ScyllaDBMonitoring e2e-test-scylladbmonitoring-tcxgl-0-wrtxn/basic-xj4vg (RV=49374) is rolled out
  STEP: Verifying that Prometheus is configured correctly @ 01/13/25 07:05:04.463
  Jan 13 07:05:04.484: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:05:05.505: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:05:06.510: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0
  Jan 13 07:05:07.663: INFO: Listing Prometheus targets: err: Get "https://172.30.183.153:9142/api/v1/targets": EOF, active: 0, dropped: 0 
[...]

  [FAILED] Timed out after 300.001s.
  The function passed to Eventually failed at github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:256 with:
  Unexpected error:
      <*url.Error | 0xc000bb6c00>: 
      Get "https://172.30.183.153:9142/api/v1/targets": EOF
      {
          Op: "Get",
          URL: "https://172.30.183.153:9142/api/v1/targets",
          Err: <*errors.errorString | 0x49bc800>{s: "EOF"},
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:291 @ 01/13/25 07:10:04.483
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring.init.func2.2(0xc0000acd00)
    	github.com/scylladb/scylla-operator/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:291 +0x1670
    reflect.Value.call({0x1ef9000?, 0xc00076b690?, 0x13?}, {0x2440919, 0x4}, {0xc000010f48, 0x1, 0x1?})
    	reflect/value.go:581 +0xca6
    reflect.Value.Call({0x1ef9000?, 0xc00076b690?, 0x363d730?}, {0xc000010f48?, 0x0?, 0x0?})
    	reflect/value.go:365 +0xb9 
```
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-latest-e2e-openshift-aws-parallel/1878683646043361280

### PR DESCRIPTION
**Pull request by mflendrich**
Disables the ScyllaDBMonitoring test on OpenShift. We have decided ([here](https://github.com/scylladb/scylla-operator/issues/2319#issuecomment-2643287819)) that we won't support ScyllaDBMonitoring in its current form (spinning up a Prometheus) on OpenShift and will instead implement #2490.

Resolves #2318
Resolves #2319

I wanted to avoid calling out test cases by name in the CI machinery and therefore introduced a "tag" concept as a simplistic approach at https://github.com/scylladb/scylla-operator/issues/2448.
I think that the right long-term solution will be to define a number of test "suites" https://github.com/scylladb/scylla-operator/issues/2448 and have a proper grid for test configurations.

One failure is expected in the parallel suite and will be handled separately: https://github.com/scylladb/scylla-operator/issues/2489

### CODE REVIEW

**Comment by mflendrich** [comment]
@zimnx this is ready for review. I seem to be missing `override` permissions.

The e2e-openshift-aws-parallel failure is expected as the PR description states

> One failure is expected in the parallel suite and will be handled separately: https://github.com/scylladb/scylla-operator/issues/2489

File: test/e2e/set/scylladbmonitoring/scylladbmonitoring.go [hunk 1]
```diff
@@ -132,7 +132,8 @@ var _ = g.Describe("ScyllaDBMonitoring", func() {
 		return fmt.Sprintf("with %q monitoring type", e.Type)
 	}
 
-	g.DescribeTable("should setup monitoring stack", func(e *entry) {
+	// Disabled on OpenShift because of https://github.com/scylladb/scylla-operator/issues/2319#issuecomment-2643287819
+	g.DescribeTable("should setup monitoring stack TESTCASE_DISABLED_ON_OPENSHIFT", func(e *entry) {
```
Comment (zimnx) [inline test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:136]: Would it be possible to extend these labels and skip based on it?

https://github.com/scylladb/scylla-operator/blob/e0c2125e99fbd5f97ccbb1f3ecf7484a987c499c/test/e2e/framework/meta.go#L17-L26

Comment (zimnx) [reply test/e2e/set/scylladbmonitoring/scylladbmonitoring.go:136]: discussed offline

**Review by zimnx — APPROVED** [review]
/lgtm
