### PR TITLE
Fix disk setup e2e assertion

### LINKED ISSUE #2308: E2E failures - Node Setup should propagate mount controller's degraded condition
Two tests out of ` Node Setup should propagate mount controller's degraded condition` suite are failing on Openshift.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-latest-e2e-openshift-aws-serial/1876955592392708096

### PR DESCRIPTION
**Pull request by zimnx**
Assertion validates if all matching Nodes of test NodeConfig have Degraded condition set, but only on one of them test tries to mess around the disks. In case when there're more than 1 matching Nodes this always fails.

To fix that, test picks up one of the nodes and validates whether expected conditions are set for chosen one.

Resolves #2308

### CODE REVIEW

File: test/e2e/set/nodeconfig/nodeconfig_disksetup.go [hunk 1]
```diff
@@ -428,11 +427,12 @@ var _ = g.Describe("Node Setup", framework.Serial, func() {
 
 				return nc
 			},
-			preNodeConfigCreationFunc: func(ctx context.Context, nc *scyllav1alpha1.NodeConfig) func(context.Context) {
+			preNodeConfigCreationFunc: func(ctx context.Context, nc *scyllav1alpha1.NodeConfig, nodeUnderTest *corev1.Node) func(context.Context) {
```
Comment (mflendrich) [inline test/e2e/set/nodeconfig/nodeconfig_disksetup.go:430]: Did you consider passing just a resource name instead of the whole node resource?

I am not familiar enough with the code to make a judgment call, but passing an entire resource to the deferred function where just a name is needed might lead to (unjustified) implied guarantee of the resource contents being up-to-date.

**Comment by mflendrich** [comment]
LGTM - one nit attached

**Review by mflendrich — APPROVED** [review]
/lgtm

**Comment by zimnx** [comment]
Let me validate if test indeed passed on non-required openshift serial before merge
/hold

**Comment by zimnx** [comment]
One of the tests that was supposed to be fixed by this change failed, but on later stage and with different root cause. The other test will be fixed in other PR. Since required jobs are green, i'm merging this and will continue working on fixing entire openshift suite.

/hold cancel
