### PR TITLE
fix: narrow identity service selector down to scylla nodes only

### LINKED ISSUE #3407: Identity service selector also matched cleanup job pods
We were adding node to a scylladb cluster, once the new node is up, the operator is scheduling cleanup job pods. Around the same time we were triggering deployment on the db client, when the new client pod starts, gocql client reported this error  `gocql: unable to create session: unable to connect to the cluster, last error: unable to discover protocol version: dial tcp connect: connection refused`.

The db client is using identity service to connect the scylladb cluster. We noticed that the identity service selector is like this
 ```
  selector:
    app: scylla
    app.kubernetes.io/managed-by: scylla-operator
    app.kubernetes.io/name: scylla
    scylla/cluster: <cluster-name>
```

Above selector end up matching both actual scylladb pods and the cleanup job pods. The ideal setup is to have the service selector only match with the actual scylladb pods

Operator version: 1.16.2

### PR DESCRIPTION
**Pull request by czeslavo**
**Description of your changes:**

Adds `scylla-operator.scylladb.com/pod-type: scylladb-node` to the identity service selector to prevent it from matching other cluster pods (e.g., cleanup job's ones) and causing connection issues.

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/scylladb/scylla-operator/issues/3407

### CODE REVIEW

File: pkg/naming/labels.go [hunk 1]
```diff
@@ -34,6 +34,15 @@ func ScyllaDBNodesPodsLabelsForScyllaCluster(sc *scyllav1.ScyllaCluster) map[str
 	return labels
 }
 
+// IdentityServiceSelectorLabels returns label keys and values used as the pod selector
+// for the identity service of the given ScyllaDBDatacenter.
+// It restricts the selector to only match ScyllaDB node pods, excluding other (e.g., cleanup job pods).
+func IdentityServiceSelectorLabels(sdc *scyllav1alpha1.ScyllaDBDatacenter) map[string]string {
```
Comment (rzetelskik) [inline pkg/naming/labels.go]: nit: perhaps we could reuse `ScyllaDBNodePodLabels` and optionally clean up the existing functions with similar purpose (e.g. `ScyllaDBNodesPodsLabelsForScyllaCluster`) by making the naming more uniform?

File: pkg/controller/scylladbdatacenter/resource_test.go [hunk 2]
```diff
@@ -2751,6 +2751,93 @@ func TestMakeIngresses(t *testing.T) {
...
+				{Name: "agent-api", Port: 10001},
+				{Name: "prometheus", Port: 9180},
+				{Name: "agent-prometheus", Port: 5090},
+				{Name: "node-exporter", Port: 9100},
+				{Name: "thrift", Port: 9160},
+			},
+		},
+	}
+	if !reflect.DeepEqual(got, expected) {
+		t.Errorf("identity service selector differs from expected:\n%s", cmp.Diff(expected, got))
```
Comment (rzetelskik) [inline pkg/controller/scylladbdatacenter/resource_test.go]: it seems that the equality test checks more than just the selector so the message is confusing

File: pkg/naming/labels.go (hunk 1 above)
Comment (czeslavo) [reply pkg/naming/labels.go]: Reused `ScyllaDBNodePodLabels` and renamed `ScyllaDBNodesPodsLabelsForScyllaCluster` to `ScyllaDBNodePodsSelectorLabelsForScyllaCluster` to match the pattern (`ScyllaCluster` variants get the explicit `ForScyllaCluster` suffix).

File: pkg/controller/scylladbdatacenter/resource_test.go (hunk 2 above)
Comment (czeslavo) [reply pkg/controller/scylladbdatacenter/resource_test.go]: Fixed.

**Review by rzetelskik — APPROVED** [review]
/lgtm
