### PR TITLE
Fix NodeConfigPod controller to exclusively enqueue and sync Scylla Pods

### LINKED ISSUE #1119: Scylla is patching unrelated config maps
**Describe the bug**

Scylla is patching some of our config maps, removing the `controllerRef` field. These config maps are unrelated to scylla.

It seems to happen when config map additions are observed in `nodeconfigpod/controller.go`. The owners are enqueued, but having inspected the code, it seems that there is no check that this is a scylla pod (like what happens in `addPod`). Eventually the pod is being synced and the `controllerRef` on the config map is removed.

I have a change that also performs the check from `addPod` in `enqueueOwner`, I can make a PR if that's the desired solution.

**To Reproduce**
Adding a config map with a `controllerRef` and the controller pod running in the same namespace should cause this problem.

**Logs**
```
nodeconfigpod/controller.go:265] "Observed addition of ConfigMap" ConfigMap="default/<unrelated-cm>"
nodeconfigpod/controller.go:177] "Enqueuing owner" ConfigMap="default/<unrelated-cm>" Pod="default/<unrelated-pod>"
nodeconfigpod/controller.go:139] "Enqueuing Pod" Pod="default/<unrelated-pod>"
nodeconfigpod/sync.go:74] "Started syncing Pod" Pod="default/<unrelated-pod>" startTime="2022-12-12 09:31:35.922543176 +0000 UTC m=+522.945119537"
controllertools/configmapmanager.go:106] "Patching ConfigMap to remove its controllerRef" ConfigMap="default/<unrelated-cm>" ControllerRef="v1/Pod:<unrelated-pod>"
nodeconfigpod/sync.go:76] "Finished syncing Pod" Pod="default/<unrelated-pod>" duration="16.360041ms"
```

**Environment:**
 - Scylla version: 5.1.0
 - Scylla-operator version: e.g.: 1.7.4

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:**
As described in https://github.com/scylladb/scylla-operator/issues/1119, currently the NodeConfigPod controller removes ownerReferences from *any* ConfigMap that has a controllerRef to *any* Pod. This is undesired as the controller shouldn't affect any resources that the operator doesn't manage. This PR adds a condition verifying whether the owner of the ConfigMap is a Scylla Pod.

**Which issue is resolved by this Pull Request:**
Resolves #1119

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
lgtm, thanks

File: pkg/controllerhelpers/handlers.go [hunk 1]
```diff
@@ -89,29 +89,41 @@ func (h *Handlers[T]) EnqueueAll(depth int, untypedObj kubeinterfaces.ObjectInte
...
+			return
+		}
+
+		if owner.GetUID() != controllerRef.UID {
+			utilruntime.HandleError(err)
+			return
+		}
+
+		if precondition(owner) {
+			klog.V(4).InfoSDepth(depth, "Enqueuing owner", append([]any{"OwnerGVK", h.gvk, "OwnerRef", klog.KObj(owner), "OwnerUID", owner.GetUID()}, getObjectLogContext(obj, nil)...)...)
```
Comment (tnozicka) [inline pkg/controllerhelpers/handlers.go:115]: nit: would it be better to make the function extendable and use  `'!precondition` pattern?

File: pkg/controllerhelpers/handlers.go [hunk 2]
```diff
@@ -89,29 +89,41 @@ func (h *Handlers[T]) EnqueueAll(depth int, untypedObj kubeinterfaces.ObjectInte
 	}
 }
 
-func (h *Handlers[QT]) EnqueueOwner(depth int, obj kubeinterfaces.ObjectInterface, operation HandlerOperationType) {
-	controllerRef := metav1.GetControllerOf(obj)
-	if controllerRef == nil {
-		return
-	}
+func (h *Handlers[QT]) EnqueueOwnerIf(precondition func(QT) bool) EnqueueFuncType {
+	return func(depth int, obj kubeinterfaces.ObjectInterface, operation HandlerOperationType) {
```
Comment (tnozicka) [inline pkg/controllerhelpers/handlers.go:93]: this one could be a named function

File: pkg/controllerhelpers/handlers.go [hunk 3]
```diff
@@ -89,29 +89,41 @@ func (h *Handlers[T]) EnqueueAll(depth int, untypedObj kubeinterfaces.ObjectInte
 	}
 }
 
-func (h *Handlers[QT]) EnqueueOwner(depth int, obj kubeinterfaces.ObjectInterface, operation HandlerOperationType) {
-	controllerRef := metav1.GetControllerOf(obj)
-	if controllerRef == nil {
-		return
-	}
+func (h *Handlers[QT]) EnqueueOwnerIf(precondition func(QT) bool) EnqueueFuncType {
```
Comment (tnozicka) [inline pkg/controllerhelpers/handlers.go:92]: We should distinguish the function name from those that do that do the work as this one returns a function - those usually have `Func` suffix. How about `EnqueOwnerWithConditionFunc`

File: pkg/controllerhelpers/handlers.go [hunk 4]
```diff
@@ -89,29 +89,41 @@ func (h *Handlers[T]) EnqueueAll(depth int, untypedObj kubeinterfaces.ObjectInte
...
+			utilruntime.HandleError(err)
+			return
+		}
+
+		if owner.GetUID() != controllerRef.UID {
+			utilruntime.HandleError(err)
+			return
+		}
+
+		if precondition(owner) {
```
Comment (tnozicka) [inline pkg/controllerhelpers/handlers.go:114]: actually similarly to
https://github.com/scylladb/scylla-operator/blob/c5c6c6ffabcacf504e7f39263da377a755f276a1/pkg/controller/nodeconfigpod/controller.go#L202-L216
would it be more generic to customize the enqueue function?

**Review by tnozicka — COMMENTED** [review]
I think we should also add the check to sync too. Handlers are more about optimization, which is good as well, but there should be a single point of enforcement.

File: pkg/controllerhelpers/handlers.go (hunk 4 above)
Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go:114]: It would, and that's what I wanted to do initially, but with `enqueueOwner` you'd have to duplicate the entire logic of extracting the owner.

Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go:114]: i meant to plumb `enqueue` func, not `enqueueOwner` although that would need to pass it as well

File: pkg/controllerhelpers/handlers.go (hunk 2 above)
Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go:93]: How? It uses a closure to pass the precondition. Unless you just meant assigning the anonymous func to a variable and returning it?
```
a := func(...) {...}
return a
```

File: pkg/controller/nodeconfigpod/controller.go [hunk 5]
```diff
@@ -231,26 +225,36 @@ func (ncpc *Controller) updatePod(old, cur interface{}) {
 	)
 }
 
+func isScyllaPod(pod *corev1.Pod) bool {
+	// TODO: extract and use a better label, verify the container
```
[the remark this answers is not in the document]
Comment (rzetelskik) [reply pkg/controller/nodeconfigpod/controller.go:229]: that's a leftover so I wasn't exactly sure what the author meant here :stuck_out_tongue:
I removed "extract and" from the TODO comment

**Review by zimnx — DISMISSED** [review]

File: pkg/controller/nodeconfigpod/sync.go [hunk 6]
```diff
@@ -39,6 +39,11 @@ func (ncpc *Controller) sync(ctx context.Context, key string) error {
 		return fmt.Errorf("can't list pods: %w", err)
 	}
 
+	_, hasScyllaLabel := pod.Labels[naming.ClusterNameLabel]
```
Comment (tnozicka) [inline pkg/controller/nodeconfigpod/sync.go:42]: can labels be nil? you've also made a function handling that int this PR

File: pkg/controller/nodeconfigpod/sync.go [hunk 7]
```diff
@@ -39,6 +39,11 @@ func (ncpc *Controller) sync(ctx context.Context, key string) error {
...
+	if !hasScyllaLabel {
+		return nil
```
Comment (tnozicka) [inline pkg/controller/nodeconfigpod/sync.go:44]: this should log a warning given we also pre-filter in the handlers unless there is some good path how it can land here in which case I'd still log it at least at info 4

File: pkg/controllerhelpers/handlers.go (hunk 2 above)
Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go:107]: nvm, it reads some of the object data as well, so it would have too many args to be a free standing function

File: pkg/controllerhelpers/handlers.go (hunk 4 above)
Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go]: I wanted to avoid duplication a version of the function in every variant (enqueue*, enqueueOwner*), see
https://github.com/tnozicka/scylla-operator/commit/803da0be8c47cd7f66fffed1edb2cf5d4c0ca568

Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go]: I see, thanks. Would you get rid of the `WithFilter` func though? I left it in as it allows for adding custom enqueue funcs without duplicating code.

File: pkg/controller/nodeconfigpod/sync.go (hunk 6 above)
Comment (rzetelskik) [reply pkg/controller/nodeconfigpod/sync.go]: good point, I missed that. Moved func to `naming` and used it here as well.

File: pkg/naming/labels.go [hunk 8]
```diff
@@ -81,3 +82,17 @@ func mergeLabels(l1, l2 map[string]string) map[string]string {
 	}
 	return res
 }
+
+func IsScyllaPod(pod *corev1.Pod) bool {
```
Comment (tnozicka) [inline pkg/naming/labels.go:86]: i think this would be better fit for `/pkg/controllerhelpers`

File: pkg/controllerhelpers/handlers.go (hunk 4 above)
Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go]: The default rule is we don't leave the functions that are not used and bring them when needed.

I don't think it brings simplification because in this case, where the filtering isn't done in the middle, a composition can easily replace it, if not be even more readable:
```
func myEnqueue() {
 // filter
 // call enqueue
}
```
the withFilter could actually be modeled this way as well

Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go]: You're right, it's a bit cleaner to compose it this way. Updated. I hope we're on the same page now and we can merge it?

Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go]: > I don't think it brings simplification because in this case, where the filtering isn't done in the middle, a composition can easily replace it

My point was that the with filter isn't needed at all
```
func (ncpc *Controller) enqueueScyllaPod(depth int, obj kubeinterfaces.ObjectInterface, op controllerhelpers.HandlerOperationType) {
	if !controllerhelpers.IsScyllaPod(pod.(*corev1.Pod)) {
		return
	}

	ncpc.handlers.Enqueue(depth+1, obj, op)
}
```

Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go]: It's not *needed*, but it abstracts away the depth increment nicely

**Review by tnozicka — DISMISSED** [review]
/approve
/lgtm

**Comment by rzetelskik** [comment]
rebased on current master, @zimnx please approve

**Review by zimnx — APPROVED** [review]
