### PR TITLE
Fix NodeConfig controller handlers to react on related object updates

### LINKED ISSUE #2001: ServiceAccount and other objects managed by NodeConfig are not reconciled on update
I've tried to delete our managed hash from `scylla-node-config` ServiceAccount and it never made it back.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-06-20T12:35:52Z"
  labels:
    foo: bar2
    scylla-operator.scylladb.com/node-config-name: scylla-node-config
  name: scylla-node-config
  namespace: scylla-operator-node-tuning
  resourceVersion: "554112"
  uid: cea11e93-fb23-468c-a092-ceb6c45ab8e5
```

The issue is that the handlers use `EnqueueOwner` but the objects don't have a controllerRef because they are singletons shared by multiple NodeConfigs.

Stems from https://github.com/scylladb/scylla-operator/pull/1971#discussion_r1662510514

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR fixes the handlers so the reconciled objects that don't have ownerRefs on them requeue the NodeConfigs. Given they are shared, they need to requeue all of them but the number of NodeConfigs is usually low single digit number anyway.

**Which issue is resolved by this Pull Request:**
Resolves #2001

### CODE REVIEW

File: pkg/controllerhelpers/handlers.go [hunk 1]
```diff
@@ -93,6 +93,16 @@ func (h *Handlers[T]) EnqueueAll(depth int, untypedObj kubeinterfaces.ObjectInte
 	h.EnqueueAllFunc(h.Enqueue)(depth+1, untypedObj, op)
 }
 
+func (h *Handlers[T]) EnqueueAllWithUntypedFilterFunc(filterFunc func(kubeinterfaces.ObjectInterface) bool) EnqueueFuncType {
```
Comment (rzetelskik) [inline pkg/controllerhelpers/handlers.go:96]: you'd cover more use cases with

```
func (h *Handlers[T]) EnqueueWithUntypedFilterFunc(filterFunc func(kubeinterfaces.ObjectInterface) bool) EnqueueFuncType {
	return func(depth int, untypedObj kubeinterfaces.ObjectInterface, op HandlerOperationType) {
		if !filterFunc(untypedObj) {
			return
		}

		h.Enqueue(depth+1, untypedObj, op)
	}
}
```

which you can compose to have the same functionality

```
ncc.handlers.EnqueueAllFunc(ncc.handlers.EnqueueWithUntypedFilterFunc(isManagedByNodeConfigController))
```

File: pkg/controller/nodeconfig/controller.go [hunk 2]
```diff
@@ -73,6 +74,15 @@ type Controller struct {
 	operatorImage string
 }
 
+func isManagedByNodeConfigController(obj kubeinterfaces.ObjectInterface) bool {
+	labels := obj.GetLabels()
+	if labels == nil {
+		return false
+	}
```
Comment (rzetelskik) [inline pkg/controller/nodeconfig/controller.go:81]: nit: unnecessary

**Review by rzetelskik — COMMENTED** [review]
one comment and one nit, rest lgtm

File: pkg/controllerhelpers/handlers.go (hunk 1 above)
Comment (tnozicka) [reply pkg/controllerhelpers/handlers.go:96]: notice the different argument types, those do not compose

File: pkg/controller/nodeconfig/controller.go (hunk 2 above)
Comment (tnozicka) [reply pkg/controller/nodeconfig/controller.go:81]: many object definitions may not have the labels map initialized, this feels safe to avoid panics

File: pkg/controllerhelpers/handlers.go (hunk 1 above)
Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go:96]: copy-pasted from my comment https://github.com/rzetelskik/scylla-operator/commit/8c8f4b4f4fa616d3dbdeed26e869e7b980a8c5f2, compiles for me

File: pkg/controller/nodeconfig/controller.go (hunk 2 above)
Comment (rzetelskik) [reply pkg/controller/nodeconfig/controller.go:81]: > many object definitions may not have the labels map initialized

yes, but you can safely read in that case anyway.
[`A nil map is equivalent to an empty map except that no elements may be added.`](https://go.dev/ref/spec#Map_types)

You can still prefer to do this imo, hence a nit

Comment (tnozicka) [reply pkg/controller/nodeconfig/controller.go:81]: not a nit, you are correct :+1:

**Review by zimnx — APPROVED** [review]
lgtm
/assign rzetelskik

File: pkg/controller/nodeconfig/controller.go (hunk 2 above)
Comment (tnozicka) [reply pkg/controller/nodeconfig/controller.go]: fixed

File: pkg/controllerhelpers/handlers.go (hunk 1 above)
Comment (rzetelskik) [reply pkg/controllerhelpers/handlers.go:96]: ok, my bad, these are not equivalent

**Review by rzetelskik — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
/retest
(likely slow clusterip again, need to find the link later)
